sourcegraph/src-cli

Gopkg.lock
Gopkg.toml
cmd/src/api.go
vendor/github.com/kballard/go-shellquote/LICENSE
vendor/github.com/kballard/go-shellquote/README
vendor/github.com/kballard/go-shellquote/doc.go
vendor/github.com/kballard/go-shellquote/quote.go
vendor/github.com/kballard/go-shellquote/unquote.go

Previously, whitespace in the GraphQL input could get compressed away.
curl commands now look like this:
```
curl \
-H 'Authorization: token abcdef' \
-d \{\"query\":\"query {  currentUser { username } }\",\"variables\":\{}} \
sourcegraph.com/.api/graphql
```

Escape arguments to curl

---

cmd/src/api.go
cmd/src/cmd.go
cmd/src/main.go
cmd/src/repos.go
cmd/src/repos_enable_disable.go
cmd/src/repos_list.go

This PR adds a new top-level command `src repos` (alias: `src repo`) with three new subcommands: `src repos list`, `src repos enable` and `src repos disable`.
For command-specific examples see the help flag (`src repos list -h`). In this section I'll write examples of how you can combine these for useful effects.
The following will list *all* repositories on Sourcegraph that are disabled, while excluding enabled ones:
```bash
src repos list -first=-1 -disabled -enabled=false
```
(add ` -query='github.com/slimsag/'` to match a query string if you only want a subset, or pipe to grep)
The following will enable any disabled repository on Sourcegraph whose name matches the query string `github.com/slimsag/`
```bash
src repos list -first=-1 -disabled -enabled=false -query='github.com/slimsag/' …
```

Add `src repos list|enable|disable` commands

---

cmd/src/cmd.go
cmd/src/extensions.go
cmd/src/extensions_get.go
cmd/src/extensions_list.go
cmd/src/extensions_publish.go
cmd/src/extensions_publish_test.go
cmd/src/main.go

Adds the following subcommands for managing extensions:
- src extensions list
- src extensions get
- src extensions publish
These are marked as experimental. The API that they use is not yet deployed to Sourcegraph.com.

add extensions subcommands

---

appveyor.yml
cmd/src/config.go
cmd/src/config_edit.go
cmd/src/config_get.go
cmd/src/config_list.go
cmd/src/format.go
cmd/src/main.go

This adds the following subcommands:
- src config get (for seeing final merged configuration)
- src config edit (for updating or overwriting settings)
- src config list (for listing all configuration subjects)

feat: add config subcommand to get/list/edit config

---

cmd/src/users.go
cmd/src/users_list.go
cmd/src/users_tag.go

User tags are used for internal Sourcegraph feature flags to enable certain features for specific users.

feat: add users tag subcommand to add/rm user tags, and listing users by tag

---

cmd/src/search.go

See https://github.com/sourcegraph/sourcegraph/pull/551 for details. Bad value for elapsedMilliseconds should not be coming back from the server on new versions.
Not sure how releases work so I'll leave that part up to you guys.

remove elapsedMillisecond hack now that backend is fixed

---

README.md
cmd/src/extsvc.go
cmd/src/extsvc_edit.go
cmd/src/extsvc_list.go
cmd/src/main.go
cmd/src/repos_list.go
cmd/src/testdata/search_formatting/basic-diff.want.txt

This PR adds support for querying repositories by name (e.g. `/secretrepos/`) and passing that list of repositories into a command that adds them to the `exclude` list in the external service configuration.
For example, it is possible to write this script now to add all repositories with `/secretrepos/` in their name to the exclusion list of all external services:
```
repos_to_exclude=$(src -config=./src-config.json repos list -first="-1" -names-without-host -query="/secretrepos/")
extsvcs=$(src -config=./src-config.json extsvc list -f '{{range .Nodes}}{{.id}} {{end}}')
echo "$extsvcs" | xargs -n1 -I {} src -config=./src-config.json extsvc edit -id '{}' -exclude-repos "$repos_to_exclude"
```
Previously we maintained backwards compatibility for `setRepositoryEnablement` in the GraphQL API …

Add support for programmatically excluding repos via external service config

---

cmd/src/repos_list.go
cmd/src/search_test.go

REPO_URI has been deprecated for many months. This is the only known client of
the deprecated enum.
Part of https://github.com/sourcegraph/sourcegraph/issues/680

repos: Use REPOSITORY_NAME for order by

---

cmd/src/campaigns.go
cmd/src/campaigns_add_changesets.go

This adds the changesets with the given external IDs to the given
campaign.
$ src campaigns add-changesets -campaign-id Q2FtcGFpZ246NA== -repo-name github.com/sourcegraph/sourcegraph 5016 5017 5018
Created 3 changesets.
Added changeset to campaign. Changesets now in campaign: 10
(These are mostly due to how our API works with batches and could be fixed on the API side, collecting these just here for documentation/transparency)
* When one of the changeset already exists, the command fails with:
```
[
{
"message": "pq: duplicate key value violates unique constraint \"changesets_repo_external_id_unique\"",
"path": [
"createChangesets"
]
}
]
```
* When one of the external IDs specified is invalid (non existant, for example), it creates the rest silently but returns an error message for the …

Add `campaigns add-changesets` subcommand

---

cmd/src/campaigns.go
cmd/src/campaigns_list.go

This allows the users to list campaigns and get the campaign IDs they
need to use the `campaigns add-changesets` command.
The default rendering template is `{{.ID}}: {{.Name}}` but users can
specify more fields or get a JSON dump of all of them with the described
`{{.|json}}` pipe:
$ src campaigns list -first 1
Q2FtcGFpZ246NA==: testing the src cli
$ src campaigns list -first 1 -f '{{. |json}}' | jq .
{
"ID": "Q2FtcGFpZ246NA==",
"Name": "testing the src cli",
"Description": "This campaign is here to test the `src` cli tool.",
"CreatedAt": "2019-09-20T05:49:54Z",
"UpdatedAt": "2019-09-20T13:07:55Z",
"Changesets": {
"Nodes": [
{
"ID": "Q2hhbmdlc2V0OjM1",
"State": "CLOSED",
"ReviewState": "APPROVED",
"Repository": {
"ID": "UmVwb3NpdG9yeTo0Mg==",
"Name": "github.com/sourcegraph/sourcegraph" …

Add `campaigns list` subcommand

---

cmd/src/campaigns_add_changesets.go

I don't know how I previously came up with 4, but as it turns out if you
run this
src campaigns add-changesets -campaign='Q2FtcGFpZ246MQ==' -repo-name=github.com/sourcegraph/sourcegraph 33 44 55 66
The IDs `33` and `44` are ignored.
This fixes the issue.

Fix "off by two" error when checking for args

---

cmd/src/main.go

This fixes #50
(Note: I conciously chose to do this when adding the command, because it's an experimental feature that needs to be enabled with a feature flag, so I wasn't sure whether we should already advertise it)

Add `campaigns` subcommand to help output

---

cmd/src/lsif_upload.go

LSIF uploads use a different authentication mechanism: LSIF upload tokens.

LSIF: drop access token

---

cmd/src/lsif_upload.go

PR https://github.com/sourcegraph/sourcegraph/pull/6227 changed the
status code from `201` to `202`.
That broke the check here and resulted in an `error: 202 Accepted` being
printed.
And the exit code is checked in
https://github.com/sourcegraph/lsif-upload-action, which runs on every
PR in sourcegrah/sourcegraph

Check for status code 202 on LSIF upload

---

cmd/src/lsif_upload.go

Sometimes there's a leading slash in git URIs:
```
git remote -vv
origin	git@github.com:/sourcegraph/lsif-java (fetch)
origin	git@github.com:/sourcegraph/lsif-java (push)
```

LSIF: strip slash prefix

---

cmd/src/lsif_upload.go

The error returned by the server is `must provide github_token` (see https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c46dd67b4682266cae719ac380f5a4ca694509db/-/blob/enterprise/internal/codeintel/lsifserver/proxy/auth.go#L45:47).

fix matching of missing-github-token error

---

cmd/src/extensions.go
cmd/src/extensions_list.go

The extension manifest used to contain a "title" field, but that was phased out a while ago in favor of just having a name. The `src extensions list` command and other subcommands still tried to fetch the manifest title, which resulted in the following error:
```
GraphQL errors:
[
{
"locations": [
{
"column": 9,
"line": 29
}
],
"message": "Cannot query field \"title\" on type \"ExtensionManifest\"."
}
]
```
This fixes the GraphQL query to not use the (nonexistent) title field anymore.

fix graphql extensions query

---

cmd/src/lsif_upload.go

LSIF job resources have been replaced by upload resources. This generates a non-404ing link.

Generate the correct ID and link for LSIF uploads.

---

cmd/src/search.go
cmd/src/testdata/search_formatting/highlight-structural-search.test.json
cmd/src/testdata/search_formatting/highlight-structural-search.want.txt

I have cleaned up the logic compared to #67. Notable things:
It is hard to work with a highlighting procedure that assumes all highlights happen on one line, with the `highlight{line: 1, character: offset, length: length}` and assumption that this is relative to the `preview` string. I tried hard to make the function `applyHighlights` work for a use case where the `FileMatch` data can be used as ranges to highlight things given the file content, but eventually stopped wasting time on this and split it out to `applyHighlightsForFile`. 
To convince you that it is not a totally insane thing to want access to the file contents as opposed to making `Preview` be some kind of source of truth, I worked on trying to get some context lines to show around matches in #71 but it didn't pan out because …

add file highlighting for structural search

---

cmd/src/extensions_copy.go

A customer is having difficulty publishing language extensions to their private registry due to internet restrictions, OS package manager restrictions, and an incompatible Node version.
This PR adds the following command:
```
src extension copy -extension-id=sourcegraph/java -current-user=chris
```
Internally, it fetches the manifest and bundle from Sourcegraph.com (hard-coded) then publishes them to the current Sourcegraph instance.

Add extension copy command

---

.travis.yml

I don't see a reason why we can't use the newest version, especially since we already use `go.mod` and `go.sum` files.

Update .travis.yml to use Go 1.13.x instead of 1.10.x

---

cmd/src/campaign_plans.go
cmd/src/campaign_plans_preview.go

I think this makes a lot more sense from a users perspective, especially with the upcoming changes in https://github.com/sourcegraph/src-cli/pull/80.

Rename "campaigns plan preview" to "campaigns plan create"

---

cmd/src/actions_exec_backend_runner.go
go.mod

The github.com/shurcooL/go/ctxhttp package no longer exists, and has been moved (and updated) to golang.org/x/net/context/ctxhttp. Update the import path and go module config. No functional changes are intended. Fixes a build break apparently introduced by #80.

Update ctxhttp module path.

---

cmd/src/actions.go
cmd/src/actions_exec.go
cmd/src/actions_scope_query.go

This command is meant to help with creating action definitions. It returns the repositories that are matched by the "scopeQuery" in an action definition.
Example:
$ src actions scope-query -f ~/run-gofmt-in-dockerfile.json
github.com/sd9/ava
github.com/sd9/go-diff
github.com/sourcegraph/automation-testing
It's based on @sqs' suggestion here: https://github.com/sourcegraph/sourcegraph/issues/7850#issuecomment-577678760

Add 'src actions scope-query' command

---

cmd/src/campaigns_create.go
cmd/src/format.go

This opens a template markdown file in $EDITOR if either no `-name` or no `-desc` are given on the command line.
This is heavily inspired by the implementation of GitHub's `hub issue create`, except that it's probably 1/4 of the code.
I also took the little regex from it, to determine whether $EDITOR is a Vim and if so set the filetype to Markdown :)

Use $EDITOR to define campaign name/desc if not given

---

cmd/src/campaigns_create.go

This implements the suggestion by @keegancsmith that I saw _in the exact same moment that I hit the merge button_: https://github.com/sourcegraph/src-cli/pull/91#discussion_r371945154

Use a temp file with .md extension for 'campaigns create'

---

cmd/src/actions_exec.go

I'm not sure whether this was a deliberate decision by @sqs but it bit me when experimenting with a query in my local instance and then not getting it work in `src actions scope-query`.

Use V2 search when searching for action scopeQuery

---

README.md

When guiding a Sourcegraph colleague through using `src` with Automation the first blocker was that their `src` was talking to `sourcegraph.com`.
I realized that in this README.md here there was barely any mention of `SRC_ENDPOINT`.
This PR tries to fix that by adding a separate `Setup` section and adding quick links at the top of the README to the three most important sections: Installation, Setup, Usage.

Add a Setup section to the README and quick links

---

cmd/src/actions_exec_backend_runner.go

It seems that some point after GNU diffutils 2.8.1 the output changed from using a backtick to a single quote.
That's why the check fails even if the diff version supports it.

Make diff flag check work for GNU diffutils 3.3

---

README.md

There's a bug in 3.12 that doesn't allow curl to work properly on the download URL. This updates the readme to indicate that it's supported 3.13 and later to stop people from running into this issue.
Closes https://github.com/sourcegraph/src-cli/issues/103

Bump version of sourcegraph instance useful for downloads in docs

---

cmd/src/campaigns_create.go
cmd/src/format.go

This PR adds a flag to specify a branch name when creating campaigns.

a8n: add branch flag for creating campaigns

---

cmd/src/campaigns_create.go
cmd/src/campaigns_create_test.go
go.mod
go.sum

This changes the behavior of `campaign create` to only check for the
`-branch` flag if the Sourcegraph instance's version is either
- >= 3.13
- dev
- a custom build date
I'm aware that the "custom build date" check is flaky, but what we want
at the moment is simply to say: only check for this flag if your
Sourcegraph version is newer than `3.12.x`.

Only check for -branch for Sourcegraph >= 3.13, dev or custom build

---

cmd/src/lsif_upload.go

See https://sourcegraph.slack.com/archives/CHXHX7XAS/p1581636650265900 for context.

Allow empty roots to be supplied explicitly to lsif upload command.

---

cmd/src/actions_exec.go

This fixes #112 by fixing a regression I introduced when taking over the
`src actions exec` functionality.
I lower-cased `imageContentDigest` so that users cannot set it. That had
the side effect of `src` itself not writing the `imageContentDigest`
to the cache key (because `json` needs the fields to be exported in
order to marshal/unmarshal them)
The fix here is to upper-case the field and add a separate validation
step to make sure that users don't set the cache field.

Take Docker image content digest into cache key

---

cmd/src/actions_exec.go
cmd/src/actions_scope_query.go

This should help with the problem encountered in #125 by making it easier to debug the scopeQuery.
The change here adds another logline to `src actions scope-query` when the `-v` flag is given and changes the existing log in `src actions exec` to show the scope query as it will be sent over the wire.
`unescaped.action.json`:
```json
{
"scopeQuery": "repo:github\.com\/sourcegraph\/sourcegraph$|basic-code-intel$ repohasfile:yarn.lock file:^package.json$ rxjs"
}
```
```
$ src -v action scope-query -f unescaped.action.json                                                                                                                -130-
github.com/sourcegraph/sourcegraph-basic-code-intel
```
`escaped.action.json`:
```json
{
"scopeQuery": …
```

Log scopeQuery as it will be sent to Sourcegraph

---

cmd/src/actions_exec_backend_runner.go
cmd/src/actions_exec_logger.go

This changes the `actionLogger` to show the different states of actions in repositories through colors:

Improve verbose output of src action exec

---

cmd/src/actions_exec_backend_runner.go
cmd/src/actions_exec_logger.go

I forgot to add this when introducing the new logger. This now logs when a result for a repository was found in the cache and depending on whether the result has a patch it's either bold or not bold.

Log cache hits when running 'src action exec'

---

README.md
cmd/src/actions_exec.go
cmd/src/actions_exec_backend_runner.go

This fixes #137.
Before this change `src actions exec` produced patches by doing the
following:
1. Download ZIP archive of repository
2. Unzip archive into directory A
3. Run action in directory A
4. Unzip archive into directory B
5. Run `diff A B`
6. Strip 'A' and 'B' prefixes from produced patches
The problem with this approach was that it didn't respect the .gitignore
file in a repository.
And since we run diff _outside_ the folder it's non-trivial to make it
respect the .gitignore, which contains pattern with the assumption that
the root directory is the repository.
This change here uses the following approach:
1. Download ZIP archive of repository
2. Unzip archive into directory A
3. Run `git init && git add --all --force & git commit -am "init"` in directory
4. Run action in …

Use git diff in temp repository instead of diff over directories

---

cmd/src/actions_exec.go
cmd/src/actions_exec_backend.go
cmd/src/actions_exec_logger.go
cmd/src/actions_scope_query.go
cmd/src/campaign_plans_create_from_patches.go
cmd/src/format.go

When the -create-plan flag is given the `src action exec` command will
create a campaign plan from the produced patches, making it not
necessary to pipe the output to `src campaign plan create-from-patches`.
If the execution of the action failed in a subset of the repositories,
the user is prompted and asked whether they would create a campaign plan
from the successfully produced patches or not.

Add -create-plan flag to 'src action exec'

---

cmd/src/actions_exec_logger.go

@christinaforney I hit "merge" too early in the other PR, so here's a follow-up with your suggestion.

Change wording of "cached result found" log message

---

cmd/src/actions_exec_backend_runner.go

Before, `/a` -> `/b` was the prefix for all files, so new files have the `/b` prefix and existing ones are moved.
This flag omits them.

Fix new git based diff generation file paths

---

actions.schema.json

As discussed, there were issues every now and then because the schema is not fully validated. This should cover off all cases we currently support and can probably simplify the `validateAction` method. 
Closes #151

Add json schema for actions definitions

---

cmd/src/campaigns_create.go
cmd/src/campaigns_create_test.go

Seems like shortly after we introduced the version check here our format changed: https://github.com/sourcegraph/sourcegraph/pull/8157

Handle new Sourcegraph 0.0.0+dev version

---

cmd/src/actions_exec.go
cmd/src/actions_exec_backend_runner.go
cmd/src/campaign_plans_create_from_patches.go

This implements the src CLI tasks of https://github.com/sourcegraph/sourcegraph/issues/8846
With this change src CLI uses the commit ID (instead of refspec) as the
`CampaignPlanPatch.BaseRevision` when creating a `CampaignPlan`.
It also adds the additional `baseRef` field to `CampaignPlanPatch` and
sends that to the GraphQL.
Since Sourcegraph <3.14 expects the `baseRevision` of a
`CampaignPlanPatch` to contain a ref (e.g. "refs/heads/master") we check
the Sourcegraph version and fall back to that behaviour so that
customers can use a newer src CLI version with their <3.14
instance.
With the addition of these fields to ActionRepo and CampaignPlanPatch
the cache of src CLI is now also busted when the revision of the default
branch of a repo changes.

Add BaseRef field to CampaignPlanPatch and use commitID in BaseRevision

---

cmd/src/actions_exec_logger.go
cmd/src/actions_terminal_ui.go

Previously we only directed the user to the logfile, but there are some
errors that are independent of the action's step: failing to fetch the
ZIP archive, failing to extract ZIP archive, etc.
(This addresses point 2 in https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0)
Those are not in the logfiles and as it turns out we never logged them.
This change fixes that.

Log action errors

---

cmd/src/main.go

We already had this in place, just not for `SRC_ENDPOINT`. This should fix https://github.com/sourcegraph/src-cli/issues/111 even though I cannot reproduce it with my local setup. I assume it only happens when nginx is in front of sourcegraph.

Remove trailing slash from SRC_ENDPOINT

---

cmd/src/actions_cache.go
cmd/src/actions_exec.go
cmd/src/actions_exec_backend.go
cmd/src/actions_exec_backend_runner.go

This fixes https://github.com/sourcegraph/src-cli/issues/165 and works like this:

Add -clear-cache flag to src action exec

---

cmd/src/actions_exec.go

This fixes #159.
I think we could (should?) go even higher, since most of the actions I ran take their time, especially on macOS.

Bump default action timeout from 2min to 15min

---

cmd/src/actions_exec.go

Right now we don't propagate the context to everything (most notably:
API requests). That means the program gets stuck when it's running a
portion of the code that doesn't use the context and the user hits
Ctrl-C.
To avoid that we listen for a second Ctrl-C and then exit with the
interrupt code 2.

Hard exit when user hits Ctrl-C a second time

---

cmd/src/actions_exec.go
cmd/src/cmd.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/9149
When a repository is being cloned while we execute the `scopeQuery` of
an action, the GraphQL query returns something like this:
{
"errors": [
{
"message": "repository does not exist: github.com/sourcegraphtest/alwayscloningtest",
"path": [ "search", "results", "results", 2, "defaultBranch" ]
}
],
"data": {
"search": {
"results": {
"results": [
{
"__typename": "Repository",
"id": "UmVwb3NpdG9yeTox",
"name": "github.com/sourcegraph/automation-testing",
"defaultBranch": { "name": "refs/heads/master", "target": { "oid": "3a0d12026c1349c4aefb712145433cc26c330a06" }
}
},
{
"__typename": "Repository",
"id": "UmVwb3NpdG9yeTozOTU=",
"name": "github.com/sourcegraphtest/AlwaysCloningTest",
"defaultBranch": null
}
]
}
}
}
}
There is …

Skip repositories being cloned in action exec instead of returning error

---

schema/action_stringdata.go
schema/actions.schema.json

Add cacheDirs to action definition JSON schema

---

.travis.yml

I've realized that the cause for the sporadic "artifact already exists"
error messages when releasing is that Travis runs releases on both the
`latest` and the version-specific tag.
This only runs releases when on the version-specific commit.

Fix race-condition when uploading releases

---

README.md

Just some minor improvements to the README so it's easier to get to the install/setup/usage docs.

Make docs clearer

---

cmd/src/actions_create.go

The other URL was wrong because it pointed to the HTML rendered page on GitHub, which doesn't work.

Fix action create schema url

---

cmd/src/actions_exec.go

All the cases covered by this function are caught by the JSON schema.
Tested manually by creating all these edge-cases in an action file

Remove duplicate validation code

---

cmd/src/lsif_upload.go

[This slack message](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1588793149072000) raises a concern about upload failures when the dotcom instance is having issues. This occurs when the frontend is not reachable, or a 500-level error occurs because the precise-code-intel backend is having issues.
This PR adds a flag to print the error but exit 0 when they occur so that we do not fail open-source builds when our own service is having issues.

Add flag to ignore lsif upload failures

---

appveyor.yml
cmd/src/lsif_upload.go
go.mod
go.sum
internal/codeintel/gitutil.go
internal/codeintel/gitutil_test.go
internal/codeintel/gzip.go
internal/codeintel/gzip_test.go
internal/codeintel/indexer_name.go
internal/codeintel/indexer_name_test.go
internal/codeintel/query_values.go
internal/codeintel/sanitation.go
internal/codeintel/sanitation_test.go
internal/codeintel/split_file.go
internal/codeintel/split_file_test.go
internal/codeintel/upload.go
internal/codeintel/upload_test.go

This PR introduces behavior that will only be available in Sourcegraph 3.16 (via https://github.com/sourcegraph/sourcegraph/pull/10456).
Behavioral changes:
- Moved reading the indexer name from the precise-code-intel-api-server to here so we don't have to write to disk in the upload path (before re-proxying to the bundle manager). Users can still specify the indexer name via a flag.
- Added `-json` flag to output a machine-readable to aid in integration tests. This will become more popular as we add additional precise-code-intel actions that will help indexing monorepos.
- Removed `-get-curl` for the lsif upload action as we can't guarantee a bounded number of HTTP requests anymore.
- Added support for chunking the LSIF index into parts and making several requests when the file size is …

Rewrite LSIF upload command

---

cmd/src/lsif_upload.go
internal/codeintel/indexer_name.go

See inline comment for context.

Raise buffer size when reading LSIF header

---

cmd/src/actions_exec_backend_runner.go

Previously, the patch was not complete and didn't apply in case any binary file changes were involved.
This is non-breaking. Additional changes on the frontend need to be performed so they show up though.

Add support for binary file changes

---

README.md
cmd/src/main.go

We still read from the config file but it has been undocumented so
that we can remove it at a later point.
Users should instead use the `SRC_ACCESS_TOKEN` and 
`SRC_ENDPOINT` environment variables.
Part of: https://github.com/sourcegraph/src-cli/issues/156

Deprecate config file in favour of env variables

---

cmd/src/main.go

We handle this special case so that the home directory is expanded. This
is only an issue when the path is specified using an equal sign, eg. -config=~/foo.json
We just fix this one specific edge case since config files are being
deprecated soon.
Closes: https://github.com/sourcegraph/src-cli/issues/187

Handle ~/ prefix in config path

---

cmd/src/actions_exec.go
cmd/src/actions_exec_backend.go
cmd/src/actions_exec_backend_runner.go
cmd/src/actions_exec_logger.go

Closes: https://github.com/sourcegraph/src-cli/issues/190

Display a progress bar in verbose mode

---

cmd/src/config.go
cmd/src/config_edit.go
cmd/src/config_get.go
cmd/src/config_list.go

closes https://github.com/sourcegraph/sourcegraph/issues/10419
looks like `ConfigurationSubject` was removed a while back, and `SettingsSubject` has replaced it
> SettingsSubject is something that can have settings: a site ("global settings", which is different from "site configuration"), an organization, or a user.
```
go build ./cmd/src
./src config list
./src config get
```
a variety of other `Configuration`-related fields have been listed as deprecated, so I've gone ahead and migrated them to use `Settings`

migrate Configuration usage to Settings

---

cmd/src/actions_exec.go

If output of `src actions exec` is piped we'll write the patches to stdout. Otherwise we'll use the file specified by the `-o` flag, defaulting to `patches.json'.
Closes: https://github.com/sourcegraph/src-cli/issues/202

By default, write patches to an output file

---

cmd/src/patch_sets.go

https://github.com/sourcegraph/sourcegraph/pull/11071 changes parts of our GraphQL API that make this change necessary.
In order to not break older Sourcegraph versions, we need to release this in a minor-version bump (so that older Sourcegraph versions don't recommend it) and increase the "required src-cli version" in Sourcegraph.

Handle HiddenPatches in PatchSet response

---

cmd/src/campaigns_create.go

This is part of https://github.com/sourcegraph/sourcegraph/issues/10953
and is necessary after https://github.com/sourcegraph/sourcegraph/pull/11130 removed the draft option.

Remove -draft flag from src campaigns create

---

cmd/src/actions_exec_logger.go

Closes: https://github.com/sourcegraph/src-cli/issues/215

Remove progress bar when action complete

---

cmd/src/actions_exec.go
cmd/src/actions_exec_logger.go

Part of: https://github.com/sourcegraph/src-cli/issues/202

Print instructions after patches written to file

---

CHANGELOG.md
cmd/src/main.go
cmd/src/main_test.go

This change removes the -endpoint flag
It also ensures the following:
* Both env vars override the config file.
* If a config file exists, either zero or both env vars must be
specified. It is an error if only one is specified. This is
to avoid confusion; we never merge config from the file and env vars.
Closes: https://github.com/sourcegraph/src-cli/issues/222

Remove -endpoint flag

---

release.sh

Lack of this check was the cause for two botched releases in the past
few weeks where we forgot to add the `.0` at the end.

Check that $VERSION is in MAJOR.MINOR.PATCH format in release.sh

---

CHANGELOG.md
cmd/src/actions_exec.go
cmd/src/colors.go
cmd/src/format.go
cmd/src/search.go
cmd/src/search_alert.go
cmd/src/search_alert_test.go

We have all this useful information in the web UI that comes back from GraphQL, but isn't exposed in `src`. This PR wires up a common renderer to the `actions exec` and `search` commands to render any alert that comes back in a (hopefully) human readable form.
Here are a couple of examples of it in use:
If we think this is useful, I'll add a couple of tests to the alert rendering and we can get this merged.

Render alert fields when performing searches

---

cmd/src/actions_exec.go
cmd/src/actions_exec_backend.go
go.mod
go.sum

I just bumped into that code, probably a left-over from #228.

Delete unused code and run go mod tidy

---

cmd/src/actions_exec.go
internal/campaigns/logger.go

In order to make more transparent why some repos are excluded, we now visualize better which repos are excluded because they aren't supported, and also display the hint on how to use them in non-verbose mode. In addition, up to 10 repo names will appear in the UI to get a better sense which are the unsupported ones.

Visualize unsupported repos better

---

DEVELOPMENT.md
appveyor.yml

This fixes the Appveyor part of https://github.com/sourcegraph/src-cli/issues/237 - Travis CI also needs to be updated.
After struggling to get this running with Go 1.14 I simply searched sourcegraph.com for `appveyor.yml` files 😎 
Turns out `golang/dep` has the [only configuration](https://sourcegraph.com/github.com/golang/dep@87f309484f0da00d4559dbe0ae5698f589f9a0d0/-/blob/appveyor.yml) that works.
Even switching worker images to the newest version didn't make Go 1.14 available — changing `GOROOT`, `PATH` etc. didn't help.

Use Go 1.14 on AppVeyor

---

CHANGELOG.md
cmd/src/repos_list.go

This PR removes the `clone-in-progress` flag. The repositories API option `cloneInProgress` has been deprecated and will be removed in 3.19.
This is related to https://github.com/sourcegraph/sourcegraph/pull/12043

Remove clone-in-progress flag

---

internal/campaigns/logger.go

This change in a previous PR broke the display of the progress bar:
https://github.com/sourcegraph/src-cli/pull/236/files#diff-f88fc84c78d26d5dc5fde4a5223bc866L258
Why did it break? Because the "display progress bar?"-check checked whether the just-printed data ended in a newline or not. That worked until the just mentioned change, after which every line was wrapped in "set color" and "reset color" escape codes. They wouldn't end in `\n` but in `\n\x1b[0m`.
The new check fixes the progress bar.
The other two commits fix a typo and remove an unused dependency.

Fix progress bar when previously printed text has color

---

internal/servegit/serve.go
internal/servegit/serve_test.go
internal/servegit/service.go
internal/servegit/service_test.go

This commit copy pastes the upload pack service we use in gitserver from
the Sourcegraph repo at commit d0d94c90. It is mostly copy paste, but we
remove prometheus metrics and "--strict" since we allow non-bare repos.
Previously we supported only git protocol v0. This is regarded as the
"dumb" protocol. We ran into issues of it being slow to update (requires
running git update-server-info). It also requires write access to the
files.
Git protocol v2 allows more efficient fetching and extra cool features
we may start to rely on.
Part of https://github.com/sourcegraph/sourcegraph/issues/12363
Part of https://github.com/sourcegraph/sourcegraph/issues/11707

servegit: use git protocol v2

---

cmd/src/api.go

When the trace flag is set we print to stderr the trace ID for the
request.

api: support for trace flag

---

cmd/src/servegit.go
internal/servegit/serve.go
internal/servegit/serve_test.go

This is useful functionality when setting up serve-git to understand
what it does.
Part of https://github.com/sourcegraph/sourcegraph/issues/12363

servegit: list flag to list found repositories

---

README.md

Fixed a documentation inconsistency for the `server-git` command in `README.md`

Fix `serve-git` documentation inconsistency

---

internal/api/api.go

By directly passing in the body we will also get the ContentLength
header set.
Minor: we avoid the extra buffer than json.NewEncoder uses, and isntead
directly get the buffer from json.Marshal.

api: pass in body to NewRequestWithContext

---

internal/api/api.go

I want to make authenticated requests against the Sourcegraph API which
are not via GraphQL. In particular I am experimenting with Server Sent
Events endpoint. This commit adds NewHTTPRequest to the Client
interface, which allows access to an authenticated http.Request. This
will then be used to communicate with the non-GraphQL endpoint.
I have no idea if this fits your vision for the api package. After a little thought this seemed like the cleanest way to achieve this access, but I'm not a big fan of expanding interfaces.
Side-note: We could avoid adding to both interface and impl if this package returned a Client struct (but still kept the Request interface). The call sites could then use an interface for Client to make them testable.

api: add Client.NewHTTPRequest

---

cmd/src/lsif_upload.go

This will be used by the precise code intel indexer to target a different upload route which will be authenticated via shared token rather than a github or sourcegraph (sudo) access token.

Add -upload-route flag to lsif upload

---

go.mod
go.sum
internal/api/api.go
internal/api/flags.go

This flag dumps the request and response out to stdout for any request issued via the internal/api package. This is probably only useful to people developing src-cli, but it's also pretty lightweight.
The output is very basic right now, but that's mostly because we have lots of implementation details stuck unexported in `cmd/src` that would be useful for colouring. If we land this and #268, then I'll likely rework this to use the new `Output` type.

api: add a standard -dump-requests flag

---

go.mod
go.sum

This stops retrying lsif upload requests on errors that aren't retryable (will now only retry on 500-level and network errors).

Update sourcegraph/codeintelutils version

---

cmd/src/campaigns.go
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go

This fixes #275 by splitting off a new `src campaigns preview` from `src campaigns apply`, and making the `-apply` flag meaningless.

campaigns: split apply into two subcommands

---

CHANGELOG.md
internal/campaigns/run_steps.go

campaigns: always set user config in the repo

---

cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
cmd/src/campaigns_validate.go
internal/output/_examples/main.go
internal/output/block.go
internal/output/output.go
internal/output/pending.go
internal/output/pending_simple.go
internal/output/pending_tty.go
internal/output/progress.go
internal/output/progress_simple.go
internal/output/progress_tty.go

A logic error in the indentedWriter implementation resulted in extra newlines, depending on which Block method was invoked. Adding a Close() method fixes this.
I promise some tests are coming soon.

output: fix Block newlines

---

cmd/src/campaigns_apply.go
cmd/src/campaigns_preview.go

This enforces a newline separation above and below the error block, and ensures that the preview command doesn't erroneously print a preview URL after an error.

campaigns: improve error output

---

internal/campaigns/errors.go
internal/campaigns/service.go

Previously, only the code host types were displayed when a campaign was previewed or applied with unsupported repos. This commit extends the error message to include the actual repos as well:

campaigns: show the repos that are unsupported

---

cmd/src/campaigns_common.go
cmd/src/campaigns_repositories.go
cmd/src/campaigns_validate.go
internal/campaigns/service.go

Currently, the spec sent to the server is created by json marshalling the CampaignSpec struct.
That, however makes us lose the original formatting, comments and yaml format, if used.
Since we want to show the spec that this campaign was created from in the UI, we need to retain the _original_ input.
@LawnGnome I'd like your review here, as I might be missing a point where the struct is modified, but the raw spec isn't.
Works on https://github.com/sourcegraph/sourcegraph/issues/13210

Retain original input for campaign spec

---

internal/output/progress_tty.go

If a progress bar was created with a size of zero (`bar.Max` was 0), then src-cli would crash in rendering. (This could happen if some engineering manager didn't know what they were doing when using campaigns and tried to create one with no repos found, for example.)
Instead, we just draw a zero-width bar if `bar.Max` is zero.

fix for crash when progress bars had a size of zero

---

internal/output/capabilities.go

I'd like to debug in VS Code, but termbox fails to init in that environment for some reason. Since all we want is the size, how about if we fall back to a reasonable default (80x25) in that case?

do not crash if termbox fails to init

---

internal/campaigns/executor.go

By changing the JSON marshalling of `Task` to ignore the `Template`, this makes it so that changes to the template (assuming no changes to `steps:` or `on:`) will serialize to the same JSON, so the previous run is found in the cache.
We then reuse the diff from the cache, and otherwise use the new spec.
**Testing:** I tested this manually with the hello world campaign. I _think_ everything worked correctly, and that my errors were unrelated to this feature, but I'd really appreciate someone else running a campaign and verifying that this works for them, too.
Closes [#13172](https://github.com/sourcegraph/sourcegraph/issues/13172)

Do not re-execute campaign spec steps when the diff is still valid

---

cmd/src/campaigns_common.go

-namespace is quite long and I've wished for a shorter version multiple
times now.
Apparently, though, introducing an alias can be controversial if all you
have is single-dash flags like `-namespace` (vs. `--namespace`), since
`-namespace` could then be interpreted as `-n -a -m -e ...` etc.
Not sure whether that's an _actual_ concern though, since we do have
single-letter flags already (`-v` and `-j`, for example).

Add -n as an alias for -namespace

---

cmd/src/campaigns_common.go
internal/campaigns/service.go

Not sure whether that fits your vision for how you want to show progress, @LawnGnome, but since the image pulling should be done once for all steps and not for each task/repository, I think it makes sense to pull it out.
Also tried to follow your convention of not mixing `output` into the `Service` but providing a progress callback.
This uses some large images, so don't be surprised that it takes so long.

Show progress bar when downloading Docker images

---

internal/campaigns/executor.go

At some point in the future, we may support campaigns having multiple commits. At the moment, however, we do not. This PR causes src-cli to panic if it finds multiple commits.
This also allows the situation where a result from the cache would have zero commits, which should be acceptable.

panic if a campaign fetched from the cache has multiple commits

---

CHANGELOG.md
internal/campaigns/campaign_spec.go
internal/campaigns/changeset_spec.go
internal/campaigns/executor.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This is the src-cli side of the fix for [#12769](https://github.com/sourcegraph/sourcegraph/issues/12769). ([back-end PR](https://github.com/sourcegraph/sourcegraph/pull/13574))
It implements the first part of [RFC 229](https://docs.google.com/document/d/1kDkIFQK9hiezEJrG5TfoGvsBKFKF6B6eUcKejYoX2XI/edit#), so campaign specs can have changeset templates that now look like:
```
changesetTemplate:
title: Hello World
body: My first campaign
branch: hello-world # Push the commit to this branch.
commit:
message: Append Hello World to all README.md files
author:
name: Chris Pine
email: chrispine@sourcegraph.com
published: true
```
Issues
- I don't know how to say "this version of src-cli goes with that version of the back-end".
Future work
- Consider: instead of just going with the default …

campaigns: allow user to set git commit author

---

internal/campaigns/executor.go

Before, the changesets would still be uploaded, even if the diff was empty. This fixes it.
@LawnGnome is this correct usage of the progress API, or am I working around something here?
Closes #307

Fix empty changesets being uploaded

---

internal/campaigns/service.go

These are usually empty repos with 0 branches.
Not sure if we would want to log those?
Closes #293

Skip repos without default branch

---

internal/campaigns/log.go

Closes #308 
before, the file ending wouldn't be `.log`, causing some terminals to not know how to open that file when clicking on it (hence, always have to select my fav editor, because the ending will always be different and cannot be remembered.)
Before and after:

Properly have .log file extension for temp log files

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
internal/campaigns/executor.go
internal/campaigns/log.go
internal/campaigns/run_steps.go
internal/campaigns/service.go

This addresses a customer report in which `src campaigns apply` couldn't
be run in CI because the docker-in-docker setup prohibits mounting
`/tmp` into containers.
It also fixes parts of
https://github.com/sourcegraph/src-cli/issues/316, since the temporary
directory is also where the logs are stored, but we might want to split
those locations up (in case a user wants to keep logs but not inside the
temporary directory).

Allow setting temp dir used by campaigns through flag/env var

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/campaigns/errors.go
internal/campaigns/service.go

Also fixes unsupported repositories aborting the workflow. We now simply skip those and let the user know.
Since this step can take some time, I was always confused what src-cli does. It resolves repositories apparently.
Closes https://github.com/sourcegraph/src-cli/issues/310

Add visual step for resolving repositories

---

README.md
cmd/src/login.go
cmd/src/login_test.go
cmd/src/main.go
cmd/src/main_test.go
internal/api/api.go

You can run `src login https://sourcegraph.example.com` to verify that your `src` is authenticated to access that Sourcegraph instance. If not, it'll show you friendly steps to help you get it set up.
This will simplify all of our docs and in-product text that relies on users using the CLI. The steps to get them to the right state will be just:
1. Install the Sourcegraph CLI (`src`) at https://github.com/sourcegraph/src-cli [or link to releases]
1. Run `src login SOURCEGRAPH_URL` [and we can even fill in `SOURCEGRAPH_URL` in in-product text]
Here is a screenshot of what it looks like in various states:
README section:

src login command to help users configure authentication w/access token

---

CHANGELOG.md
internal/campaigns/log.go

While looking into how we store ZIP files I realised that log files are
not cleaned up. That's not a big issue, since `/tmp` is cleaned up by
the OS, but it's still a regression and not what we intended.
Digging deeper I ended up starting at the previous for much too long
before realising that the cleanup code was simply missing :)

Fix regression and clean up log files again

---

cmd/src/campaigns_repositories.go

Previously it was really hard to tell how many repositories matched without having to scroll through the terminal output.
Before:
After:

Show total number at end of repositories command output

---

internal/campaigns/service.go

Tiny change but I think it makes a difference: instead of a 1s delay in
which we show nothing (and seem to hang) we show the spinner
immediately.

Show execution progress immediately

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
internal/campaigns/executor.go
internal/campaigns/run_steps.go
internal/campaigns/service.go
internal/output/style.go

This is the first of possibly many stabs at improving the error
reporting.

Improve error output when executing step fails

---

CHANGELOG.md
cmd/src/campaigns_common.go
go.sum
internal/campaigns/archive_fetcher.go
internal/campaigns/executor.go
internal/campaigns/run_steps.go
internal/campaigns/service.go

Copying from the CHANGELOG:
- The default behaviour of `src campaigns [preview|apply]` has been changed to retain downloaded archives of repositories for better performance across re-runs of the command.
- To use the old behaviour and delete the archives use the `-clean-archives` flag.
- Repository archives are also not stored in the directory for temp data (see `-tmp` flag) anymore but in the cache directory, which can be configured with the `-cache` flag. To manually delete archives between runs, delete the `*.zip` files in the `-cache` directory (see `src campaigns -help` for its default location)
I'm still not sure whether this is the best way to achieve the goal of
"do not delete the same zip file over and over again", because it's easy
ot have the cache fill up: if you run campaigns …

Retain repository archives across executions

---

CHANGELOG.md
cmd/src/campaigns_common.go

We had the check for git before, but lost it in the switch to the new
model.
The Docker check I added after running into a hard-to-decipher error
when trying to run `src campaigns apply` on a VM without Docker.
Here's what it looks like:

Check that Docker and git are available when executing campaign spec

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
internal/campaigns/executor.go
internal/campaigns/run_steps.go

Before this change Docker containers kept on running after the interrupt signal was sent to the process and killing it. This was a slight regression, since it was previously fixed by #169.
What this commit does is bring back the behaviour of #169 and also makes sure that we print the correct error message when we canceled a running step.
It also makes sure that we don't enqueue more tasks/steps after being canceled: that's the code in `(*executor).Start()` that aborts the `Range` call if the context has been cancelled/timed-out and aborts execution of a task if the goroutine already blocked on `x.par.Acquire()`.

Handle interrupt signal in src campaigns apply|preview

---

CHANGELOG.md
go.mod
go.sum
internal/campaigns/campaign_spec.go
internal/campaigns/executor.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This is a prototype of the option being presented in [RFC 228](https://docs.google.com/document/d/1A-5cbYGz1p1UB1eAFsIgpK5XDkvS7ZNAVKMdtBm_WY0/edit?usp=sharing). It needs to be used in conjunction with sourcegraph/sourcegraph#13476.
Note that this PR adds a dependency on https://github.com/LawnGnome/campaign-schema for schema-related code shared between this PR and sourcegraph/sourcegraph#13476; my intention is to move this to https://github.com/sourcegraph/campaignutils if accepted.
An example of the type of campaign you could run with this is:
```yaml
name: hello-world
description: Add Hello World to READMEs
​
on:
- repositoriesMatchingQuery: file:README.md r:github.com/*
- repositoriesMatchingQuery: file:README.md r:gitlab.sgdev.org
​
steps:
- run: echo Hello World | tee -a $(find …
```

campaigns: allow partial publishing of changesets

---

cmd/src/campaigns_common.go

The other status messages don't use punctuation, so let's keep them all consistent.

campaigns: remove full stop from success message

---

cmd/src/campaigns_common.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/service.go

This was used in the old architecture but has been replaced by the
TaskStatus callbacks.

Remove unused callback from Executor

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/output/emoji.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/14531 by showing a warning.
Please note that I think it should only ever be a warning, otherwise it'll be really hard to run `src campaign apply|preview` reliably in CI without some additional flags or something.

Show warning if 0 changeset specs have been created

---

cmd/src/campaign_progress_printer.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/14559 by
not printing a progress bar when 0 repositories have been matched.

Fix display of status bars when 0 repositories have been matched

---

internal/api/api.go

This gzips http requests to the backend. It relies on [this](https://github.com/sourcegraph/sourcegraph/pull/14391) and partially fixes [this](https://github.com/sourcegraph/sourcegraph/issues/12840).

gzip http requests

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_preview.go
cmd/src/campaigns_repositories.go
cmd/src/campaigns_validate.go
cmd/src/config_get.go
cmd/src/config_list.go
go.mod
go.sum
internal/api/api.go
internal/api/api_test.go
internal/api/version_check.go
internal/api/version_check_test.go
internal/campaigns/service.go

This is a follow-up to https://github.com/sourcegraph/src-cli/pull/336 and addresses this comment https://github.com/sourcegraph/src-cli/pull/336#discussion_r503788437 and the broken build (see https://github.com/sourcegraph/src-cli/pull/336#issuecomment-707605116) by
- making gzip compression for GraphQL requests an opt-in feature of the `api.Client` (vs. trying to encode every request)
- making the `gzip: bool` flag a property of the `api.Request` struct to fix the data race
- pulling the version/feature-flag check out of the `api.Client` and moving it into the `campaigns.Service` where it's used to determine whether gzip compression should be used or not
- adding back the the unit tests that came with the original implementation of the `sourcegraphVersionCheck` function
- reusing the …

Follow-up to gzip encoding of request body

---

cmd/src/campaigns_new.go

This tries to make the block comments more consistent in the template, and hopefully slightly more helpful, at the risk of being too wordy. Thoughts?

campaigns: template comment consistency

---

release.sh

I'm not saying I forgot to check the checklist in DEVELOPMENT.md before releasing today, but... uh, I'm not saying I _didn't_ forget, either.

release: add a note about DEVELOPMENT.md

---

go.mod
go.sum
internal/campaigns/campaign_spec.go
internal/campaigns/changeset_spec.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

Using the introduced triple of true/false/"draft", users can now specify to open a PR in draft mode on the code host.
I'm opening this up for review, but I need to get https://github.com/sourcegraph/campaignutils/pull/3 merged first in order to merge this PR. Hence, the `go.mod` file contains some local hackery that I need to override (no pun intended) once merged.
Another PR in the series of https://github.com/sourcegraph/sourcegraph/issues/7998 towards the first milestone, getting the syntax support ready.

Add draft option support for publish in changeset template

---

cmd/src/campaign_progress_printer.go
internal/output/progress_with_status_bars_tty.go
internal/output/status_bar.go

This fixes #348 by changing the behaviour of the
`progressWithStatusBarsTTY` to only print status bars that have been
updated/reset.
It removes the placeholder label "Starting worker..." and simply doesn't
display status bars that don't have a value yet.
@LawnGnome can you maybe test this too? I tried to replicate different scenarios (cached, uncached, subset cached, more than numProcesses, less than numProcesses) but I'm not sure whether I caught your bug.

Print only status bars that have been activated

---

CHANGELOG.md
internal/campaigns/archive_fetcher.go

Ensure that cache dir exists before downloading ZIP archive

---

internal/campaigns/executor_test.go

This gives the test a longer timeout to ensure that we've reached
`runSteps` when the timeout kicks in, even on slow CI machines.
And it changes the "sleep" to a power-nap-sleep-loop so that we only
have to wait 100ms until the test returns.

Fix flaky executor timeout test

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
internal/campaigns/executor.go
internal/campaigns/run_steps.go
internal/output/progress_with_status_bars.go
internal/output/progress_with_status_bars_simple.go
internal/output/progress_with_status_bars_tty.go
internal/output/status_bar.go

Yesterday I noticed that when executing steps fails in a repository we simply show "No changes" in the status bars. If you execute steps in a lot of repositories that means you'll need to wait until all of them are finished to get feedback on whether one of them failed.
This changes the behaviour from this
to this:
I'm not super happy with the `StatusText()` and `SingleLineError()` methods and how to best interface them, but then again I never found wrapped errors easy to manage. If you have any ideas: let me know!

Show failed tasks as errors in statusbars

---

CHANGELOG.md
go.mod
go.sum

We now print the response body when we can't parse JSON when expected on LSIF uploads. Closes https://github.com/sourcegraph/src-cli/issues/330.

deps: Bump codeintelutils version

---

internal/campaigns/run_steps.go

With the command being in JSON it's really hard to copy and run it to
debug something.
And since we don't ever need this output in JSON, I changed the code to
log log the un-rendered version of run.Step and then the full command.

Do not marshal docker command to JSON when logging

---

CHANGELOG.md
internal/campaigns/archive_fetcher.go
internal/campaigns/archive_fetcher_nonwin_test.go
internal/campaigns/archive_fetcher_test.go
internal/campaigns/archive_fetcher_windows_test.go
internal/campaigns/run_steps.go

This fixes #365 by ensuring that files and workspaces mounted into campaign containers are world readable, writable, and executable as appropriate.

campaigns: widen permissions on mounted paths

---

CHANGELOG.md
internal/campaigns/run_steps.go

campaigns: fix cidfile lifecycle on Windows

---

CHANGELOG.md
internal/campaigns/run_steps.go

Fixes https://github.com/sourcegraph/sourcegraph/issues/15314
This adds the `--init` flag to the `docker run` command so that the
entrypoint process (`bash` in our case) is started by a init process.
That fixes the behaviour of the interrupt signal simply having no
effect.
From what I could gather that's because PID 1 (which is the
`--entrypoint` in a Docker container) is protected and cannot be killed.
But `--init` is given the PID1 is an init process, which forwards the
signal to our entrypoint and kills it, exiting afterwards.
Resources:
- https://stackoverflow.com/questions/45718967/how-do-you-kill-a-docker-containers-default-command-without-killing-the-entire-c
- https://unix.stackexchange.com/questions/457649/unable-to-kill-process-with-pid-1-in-docker-container
- …

Fix killing of unresponsive containers by adding init process

---

CHANGELOG.md
internal/campaigns/changeset_spec.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/features.go
internal/campaigns/features_test.go
internal/campaigns/service.go

The author name and e-mail fields were always sent, but the schema Sourcegraph 3.19 uses to validate changeset specs don't include these fields. Since we're doing version detection for feature flags (quirks) now anyway, let's use that to not set the author name and e-mail if they're not explicitly provided when talking to a 3.19 instance.
If the user provides an author name and/or e-mail and sends a changeset spec to a pre-3.20 instance, the request will fail, but since those are 3.20 features that's OK.

campaigns: restore pre-3.20 instance compatibility

---

CHANGELOG.md
internal/campaigns/run_steps.go

This can cause unexpected git behavior, like a different diff tool, ANSI coloring in the diff and probably other bad magic.
Closes https://github.com/sourcegraph/src-cli/issues/371

Don't use git config that might be present on the host

---

DEVELOPMENT.md
README.markdown

As @chrispine noticed when releasing 3.21.9, we have a dangling reference to Travis in our release checklist. We also still had the old CI badge kicking around, so let's fix them both at once.

CI: remove last vestiges of Travis

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go

We ran into an out-of-bounds panic when we had more tasks reporting as
"currently running" than the number of status bars we had.
That was due to a lack of defensive checks in the face of a possible
race condition.
The race condition leads the `PrintStatuses` method seeing more
"currently running" tasks than there can technically be.
The race condition is between the `PrintStatus` method that prints the
slices of pointers to `*TaskStatus` and the tasks themselves updating
the status non-atomatically.
At least that's what it seems like. I'm not 100% sure about the cause
yet, but I could reproduce the issue by simply injecting more statuses
at the top of `PrintStatuses`. The code here fixes it.
---
I'm still trying to find out exactly why it happens, but I do think this code should be in …

Fix out-of-bounds panic in progress printer

---

CHANGELOG.md
internal/campaigns/service.go
internal/campaigns/service_test.go

This fixes #382 by fixing a regression that was introduced by #361.
When the search queries defined in a campaign spec yielded a repository
match result and file match results in the same repository, in that
order, the code would crash because of an uninitialized map.
The code here fixes it by always initializing the map.
I also added a test that reproduces the behaviour and documents how we
turn multiple search results into a list of repositories.

Fix panic when search yields repo and file matches in same repo

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_preview.go
cmd/src/campaigns_validate.go
cmd/src/cmd.go

This should stop users from running into https://github.com/sourcegraph/src-cli/issues/383

Return error if additional args passed to campaigns command

---

CHANGELOG.md
internal/campaigns/archive_fetcher.go
internal/campaigns/archive_fetcher_test.go
internal/campaigns/executor_test.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/15865
This fixes a bug where src-cli would leave partially-downloaded ZIP
files behind when the user hit Ctrl-C while a download was ongoing.
The `fetchRepositoryArchive` would then run into a context-cancelation
error when doing the request or the `io.Copy` and not clean up the file.
The code here checks whether the cause of the error is a cancelation
and, if so, cleans up the zip file.

Clean up partially-downloaded ZIP files if aborted

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go

This is super embarrassing, but ... well, here we are.

Fix status bar updates getting lost

---

cmd/src/doc.go

This generates ugly, but readable Markdown output that can be used within the Sourcegraph doc directory.
For an example of this in action, see https://github.com/sourcegraph/sourcegraph/pull/15906.

cmd: add a hidden doc command

---

DEVELOPMENT.md

This addresses @mrnugget's concern in https://github.com/sourcegraph/sourcegraph/pull/15906#pullrequestreview-534162377 around ensuring that we don't slow down generation in sourcegraph/sourcegraph while still having up to date reference docs.

release: note reference doc update requirements

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
cmd/src/campaigns_common.go
internal/campaigns/service.go

Thoughts/opinions/ideas?
TODOs:

More information in verbose mode to provide faster feedback loop

---

CHANGELOG.md
go.mod
go.sum
internal/campaigns/campaign_spec.go
internal/campaigns/execution_cache.go
internal/campaigns/execution_cache_test.go
internal/campaigns/features.go
internal/campaigns/features_test.go
internal/campaigns/run_steps.go
internal/campaigns/service.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This is the src-cli component of sourcegraph/sourcegraph#15822.
There's also a new feature flag in here to maintain backward compatibility with older Sourcegraph versions, at the cost of extra work when parsing the campaign spec. I think that's the right tradeoff.

campaigns: allow env usage in campaign steps

---

cmd/src/campaigns_common.go

Before:
$ src campaign apply -f campaign.yaml -v
flag provided but not defined: -v
Usage of 'src campaigns apply':
-allow-unsupported
Allow unsupported code hosts.
[ ... ]
You had to specify `-v` right after `src` and before `campaign [apply|preview]`.
That means everytime I wanted to switch to verbose mode I had to *edit*
the previous command instead of just append a `-v`.
Now, with this change...
... switching to verbose mode is easier than ever...
Look:
$ src campaign apply -f campaign.yaml -v
[... command runs, people are happy :D :D :D ... ]

-v everywhere! Huge quality of life improvement! Merge now!

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/campaigns/archive_fetcher.go
internal/campaigns/archive_fetcher_test.go
internal/campaigns/executor_test.go
internal/campaigns/graphql/repository.go
internal/campaigns/service.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/15070 by changing the evaluation of the `on.repository` field in the campaign spec to actually query for and use the `branch` attribute.
It queries the GraphQL API for a commit that matches the exact rev and returns an error if no commit was found.
If the campaign spec uses `repositoriesMatchingQuery` and `repository`, like this
```yaml
- repositoriesMatchingQuery: repo:automation-testing
- repository: github.com/sourcegraph/automation-testing
branch: thorstens-test-branch
```
then the second branch, `thorstens-test-branch`, is checked out and used as the base branch for the changeset.
What we don't support yet is using a revspec in the search query, like `repo:github.com/sourcegraph/automation-testing@thorstens-test-branch …

Query and use the repository.branch when defined in spec

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
internal/campaigns/service.go
internal/output/emoji.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/15790 by adding the `-skip-errors` flag.
Note: I made the conscious decision to only skip "runtime errors", i.e.: we can skip the failed step execution, or we can skip the failed importing of a changeset (see "after" screenshot). That means validation errors etc. are not skipped. Because I don't think that makes sense.

Add -skip-errors flag to src campaign apply|preview

---

CHANGELOG.md
internal/campaigns/executor.go
internal/campaigns/executor_test.go

It's totally valid and normal for empty diffs to be created when
executing campaign specs: sometimes you just don't want anything to
change, even though the repo matched the initial query. When this
happens, #313 added a check that prevents the changeset spec from being
created, and print a verbose mode message indicating that the repo was
skipped:
https://sourcegraph.com/github.com/sourcegraph/src-cli@d29ad54eff678d96fb7ebdf75ff95890dce6a1cf/-/blob/internal/campaigns/executor.go?utm_source=VSCode-1.1.0#L273-278
So far, so good. In #374, we made our empty diff handling even better by
caching the empty diff: this means that we don't have to recalculate
that nothing happened. Unfortunately, the check that exists in the cache
miss code path to skip changeset spec creation doesn't exist in …

campaigns: skip changeset spec creation for cached empty diffs

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
go.mod
go.sum
internal/campaigns/executor.go
internal/campaigns/service.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/16195 by doing two things:
1. It threads every update and read of `*TaskStatus` in `executor` through a mutex to provide a consistent view of all `[]*TaskStatus`. While we had a `sync.Map` in place it didn't protect us from race conditions, since we passed around _pointers_ to `TaskStatus` freely: the `executor` goroutines would happily write to a `*TaskStatus` and the `campaignProgressPrinter.PrintStatus` would read `[]*TaskStatus` _while they're being updated_. The `sync.Map` was useless in practice. So instead of that, I added a mutex that's used when updating a `*TaskStatus` and when reading _all_ `[]*TaskStatus` when printing the status.
2. It uses a 1-capacity semaphore to control access to the `campaignProgressPrinter` …

Fix race conditions when printing current status of tasks

---

cmd/src/campaign_progress_printer.go
cmd/src/campaign_progress_printer_test.go
internal/output/output.go
internal/output/progress.go
internal/output/progress_simple.go
internal/output/progress_tty.go
internal/output/progress_with_status_bars.go
internal/output/progress_with_status_bars_simple.go
internal/output/progress_with_status_bars_tty.go

I started with one thought: "I just wish I had _one_ test to make sure that this whole thing [the terminal UI] doesn't blow up every time I make a change" What I ended with is this. It includes a tiny VT100 "emulator".
And here's the kicker: I actually like this. It's fast to run and easy to extend and it gives me confidence that the basic rendering functionality works. Of course, the hacky injections need to be cleaned up before merging. And maybe we can get it to pass on Windows.
Opinions?
(This fixes https://github.com/sourcegraph/sourcegraph/issues/16330)

Snapshot test the terminal UI

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
cmd/src/campaign_progress_printer_test.go
cmd/src/campaigns_common.go
internal/campaigns/campaign_spec.go
internal/campaigns/execution_cache.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/features.go
internal/campaigns/service.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This is the implementation of the suggested solution for **Option B** in [RFC 265: Multiple changesets per repository](https://docs.google.com/document/d/1cXEuUdYJeK-uwZpowhorPGSAUfE87QkaLbf9r_EVRfI/edit) to produce multiple changesets in a single repository.
It depends on https://github.com/sourcegraph/sourcegraph/pull/16235. It fixes https://github.com/sourcegraph/sourcegraph/issues/14970.
**IMPORTANT**: this _only_ implements the first step in ["Defintion of success"](https://docs.google.com/document/d/1cXEuUdYJeK-uwZpowhorPGSAUfE87QkaLbf9r_EVRfI/edit#bookmark=id.rs92im1omcfo). It does **not** yet implement addressing multiple changesets in the same repository separately (that's Part2 in the RFC).
What this does is to introduce the `transformChanges` property to campaign specs (see …

Introduce `transformChanges` to campaign spec (RFC 265)

---

CHANGELOG.md
internal/campaigns/errors.go
internal/campaigns/service.go
internal/campaigns/service_test.go

I think multiple changes to this method lead to a regression where
unsupported repositories were correctly being reported as unsupported
but were still added to the final list of repositories, regardless of
whether `-allow-unsupported` was set or not.

Actually skip unsupported repos if -allow-unsupported is not set

---

CHANGELOG.md
internal/campaigns/campaign_spec.go
internal/campaigns/campaign_spec_test.go

This fixes https://github.com/sourcegraph/src-cli/issues/406 and
https://github.com/sourcegraph/src-cli/issues/404 by making sure that a
`changesetTemplate` is defined when `steps` are set.
(Since we allow using only `importChangesets` in a campaign spec, we need
to make this conditional on whether steps are set or not)

Validate spec contains changesetTemplate if steps are set

---

cmd/src/extensions_copy.go

withCfg swaps in a new config that points at dot-com but the request uses the client created above the swap and captured in the closure.

extensions: copy operation create client pointing at dot com

---

cmd/src/campaigns_common.go
internal/api/api.go
internal/api/api_test.go
internal/api/errors.go
internal/api/errors_test.go

In and around sourcegraph/sourcegraph#16687, we had a fairly lengthy discussion around how to present licensing errors to the user. Doing it in a way that is actionable for the user is fairly tricky: we don't have a simple limit directive that could be applied to the repository search, so the user is left with a campaign spec that they might still want to trial but don't know how to get to a trialable state.
This PR uses the new error code returned from sourcegraph/sourcegraph#16687 to special case licensing errors. When those are detected, a suggestion is made for how the campaign spec could be modified to be compliant with the unlicensed behaviour.
Here's how it looks:
Linked to sourcegraph/sourcegraph#15715, but it's more a bonus adventure than that issue.

campaigns: suggest alternatives when campaigns are unlicensed

---

CHANGELOG.md
cmd/src/version.go

This fixes us not using any authentication in the src version command, because the api.Client adds the Authorization header to the request automatically

Use api.Client for http request in src version

---

CHANGELOG.md
cmd/src/login.go

Allows `src login` without an argument to validate against `SRC_ENDPOINT` by default

login: default to SRC_ENDPOINT

---

CHANGELOG.md
cmd/src/config.go
cmd/src/config_edit.go

Currently, providing a `-subject` flag to `src config` does not apply it.
```
+ src config edit -subject=U2l0ZToic2l0ZSI= -property=notices '-value=[]'
GraphQL errors: 1 error occurred:
* {
"locations": [
{
"column": 39,
"line": 2
}
],
"message": "Variable \"subject\" has invalid value null.\nExpected type \"ID!\", found null."
}
```
Also, the docs state that this command can edit global config, but does not imply how, so I added an example with a workaround - let me know if there's a proper way to do this!

config: fix subjects flag, add example for editing global config

---

internal/campaigns/run_steps.go

Noticed this while reading through the code.

Remove duplication in templating helpers

---

.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.goreleaser.yml

This broke the 3.23.2 release, which was fun.
Specifically, we need to handle the deprecations of [`brews.github`](https://goreleaser.com/deprecations#brewsgithub) and [`docker.builds`](https://goreleaser.com/deprecations#dockerbuilds).
This PR also adds a new CI job to check the validity of the GoReleaser configuration, since breaking changes are apparently a Thing.

goreleaser: update to latest schema

---

.goreleaser.yml
CHANGELOG.md
cmd/src/campaigns_common.go
cmd/src/version.go
internal/campaigns/bind_workspace.go
internal/campaigns/service.go
internal/campaigns/volume_workspace.go
internal/campaigns/volume_workspace_test.go
internal/campaigns/workspace.go
internal/campaigns/workspace_test.go
internal/version/version.go

This fixes sourcegraph/sourcegraph#17172. I'm inclined to get this in before I try releasing 3.23.2 again.
The only real drawback of this PR (besides the extra lines of code) is that `src` will now always ensure the `sourcegraph/src-campaign-volume-workspace` container is available, since we don't know at the point of downloading Docker images which workspace we'll use. (To figure that out, we'd need the images, and then the snake eats itself.) Since Docker is good at caching, I'm not too concerned: this is only one extra `docker image inspect` call in any case except for the very first cold run with a new version. (Also, we can _definitely_ optimise those more later.)
Speaking of versioning, there's one other change to make this work as well: when I implemented #412, I missed that newer …

campaigns: fall back to bind workspaces when running steps with mixed users

---

CHANGELOG.md
cmd/src/lsif_upload.go
go.mod
go.sum

Add trace logging to lsif upload actions.

Add verbosity levels to lsif upload

---

CHANGELOG.md
go.mod
internal/campaigns/campaign_spec.go
internal/campaigns/execution_cache.go
internal/campaigns/execution_cache_test.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/run_steps.go
internal/campaigns/templating.go
internal/campaigns/templating_test.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This PR enables **dynamic `changesetTemplates`** in campaign specs by doing two things:
1. it adds templating support to the `title`, `body`, `branch` and `commit.message` fields in `changesetTemplate`.
2. it adds `outputs` to `steps`, which are values that are set after the step has been executed and that have _access to template variables, including the current step's output_.
This solves the problem of not being able to customize the `changesetTemplate` per repository (only `published` could be configured per repository).
With this PR, the following campaign spec works:
```yaml
name: dynamic-changeset-template
description: Hello Outputs
on:
- repository: github.com/sourcegraph/src-cli
steps:
- run: echo "Hello there!" >> message.txt && cat message.txt
outputs: …
```

Enable dynamic changesetTemplates by adding templating & steps outputs

---

cmd/src/lsif_upload.go
go.mod
go.sum

Need to wait for the codeintelutils update before this works.

codeintel: add an --associated-index-id flag for autoindexer usage

---

cmd/src/validate.go
go.mod
go.sum

This fixes #429 by switching `src validate` to use `yaml.v3`.
When trying to confirm that it still works, I found out that parsing the validate input as YAML didn't work for me, even without the change.
Both `yaml.v3` and `yaml.v2` assume that the fields in the YAML are in `snake_case` and need tags added to the struct fields to make it work with `camelCase`.
The `github.com/ghodss/yaml` works with `snake_case` and also supports the unmarshalling into a `*json.RawMessage`, which `yaml.v2` and `yaml.v3` don't support.
But since the goal was to only use a single YAML library I switched to `yaml.v3` and changed the code to work with it. I tested this locally and checked that everything's unmarshalled correctly.'
See the script here for how I explored this (and learned to curse YAML yet …

Switch 'src validate' to use yaml.v3

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/campaigns/service.go
internal/campaigns/volume_workspace.go

@eseliger noticed this one: volume workspaces were mounting their run scripts from the OS temporary directory, which could cause problems on macOS 11 + Docker 3.1. (And probably other configurations, but it worked for me on macOS 10.15.)
It should be using the same temporary directory as everything else, so let's do that.

campaigns: use the temp dir when mounting scripts in volume mode 

---

internal/campaigns/workspace.go
internal/campaigns/workspace_test.go

This can be reverted once we land #434.

campaigns: temporary switch back to bind for non-root

---

internal/campaigns/workspace_test.go

I don't know what changed but before this fix I could pretty reliably get `TestBestWorkspaceCreator` to fail by running:
```
go test -run TestBestWorkspaceCreator/different_user -count=10 ./internal/campaigns
```
It would fail with
```
--- FAIL: TestBestWorkspaceCreator (0.01s)
--- FAIL: TestBestWorkspaceCreator/different_user (0.01s)
expect.go:64: unexpected command: 1 error occurred:
* unexpected argument at position 4: have="bar" want="foo"
expect.go:108: unexpected number of commands executed: have=1 want=4
FAIL
FAIL    github.com/sourcegraph/src-cli/internal/campaigns       0.536s
FAIL
```
With the fix here I can't get it to fail anymore, so I'm 99.9% sure that the error was due to `range` over `map` not being stable and sometimes setting up the wrong assertions which would then …

Fix flaky test by using slice for stable iteration

---

internal/campaigns/executor.go

Running `:GoMetaLinter` just pointed me to this "ineffective break
statement" that I introduced in #328 with the following comment:
> It also makes sure that we don't enqueue more tasks/steps after being
> canceled: that's the code in `(*executor).Start()` that aborts the
> `Range` call if the context has been cancelled/timed-out and aborts
> execution of a task if the goroutine already blocked on
> `x.par.Acquire()`.
Well... turns out that wasn't the case, was it?
Instead the code only broke out of the `select` and continued trying to
acquire a lock.
I also suspect that this bug might have something to do with a customer
reporting that long-running containers are not stopped when hitting
Ctrl-C (https://github.com/sourcegraph/sourcegraph/issues/16026) even
after we thought the issue was …

Correctly abort on interrupt instead of going into endless loop

---

internal/exec/expect/expect.go

The comment in the diff basically describes this: we had an unintentional coupling in mocked commands with the host's binaries on its `PATH`, which is obviously bad if you're trying to mock away the environment in the first place.

testing: fix expect error when the command is not on the PATH

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/service.go

The `.Wait()` method didn't check `ctx.Done()` before and could instead
block on `x.par.Wait()`, waiting for a mutex.
I ran into this just now when my Docker became unresponsive and the
`docker run` in `(*dockerVolumeWorkspace).runScript` would block.
Ctrl-C didn't help and did *not* kill the docker process (why that
didn't happen is a separate question). But src-cli
also didn't exit because it was blocked waiting for that mutex.
So, this solves *another* case of src-cli becoming unresponsive.

Handle ctx.Done() when waiting for steps to finish

---

internal/campaigns/executor.go

The previous code could cause a panic when `ctx.Done()` returns something, the outer function returns, the `defer` is triggered and the channel closed and _only then_ the `x.pair.Wait()` returns in the goroutine.

Fix possible closed-channel-send panic

---

internal/campaigns/executor.go

This fixes https://github.com/sourcegraph/src-cli/issues/416 (hopefully)

Make 'reachedTimeout' check more resilient

---

cmd/src/campaigns_common.go
internal/output/emoji.go
internal/output/style.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/17259, but
contrary to what I stated in the original ticket, I think it makes more
sense to always link to these docs.
Why?
1. It's two lines. It doesn't hurt.
2. It's really tricky to find out exactly when to link to the docs and
when not. Especially since running the steps could result in an error
that could be fixed through the troubleshooting guide (example:
broken docker setup).
---

Link to troubleshooting docs when src campaign apply|preview fails

---

cmd/src/campaigns_common.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/repo_fetcher.go
internal/campaigns/repo_fetcher_test.go
internal/campaigns/run_steps.go

This is a second, alterantive approach to https://github.com/sourcegraph/src-cli/pull/449 for keeping archives cached across different executions.
It models `RepoZip` as a [thunk](https://en.wikipedia.org/wiki/Thunk) in a way: `RepoFetcher.Checkout()` returns a `RepoZip` that's passed around with the `Task`. Once all `Tasks` have called `Fetch()` and `Close()` only then the archive is cleaned up.

Alternative approach to keeping archives cached

---

cmd/src/campaigns_common.go

I like the troubleshooting suggestion added in #451, but I'd prefer to wrap the output, since it's quite wide right now:

campaigns: wrap the troubleshooting suggestion

---

cmd/src/campaigns_common.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/service.go
internal/campaigns/service_test.go

This is a follow-up to #442 and ensures that changeset specs are not
getting silently lost by validating that multiple changeset specs in the
same repository have different branches.
I decided to make this a separate step _after_ the execution of the
steps so that users can leverage the cache. That allows them to change
the campaign spec and then rerun the command after they get this error,
vs. the execution being aborted after running into this error (if we'd
do the check inside executor).
Screenshot:

Check for branch duplicates after creating changeset specs

---

.dockerignore
.goreleaser.yml
DEVELOPMENT.md
Dockerfile
Dockerfile.release

Combined with the new documentation, this should make it easier to test Renovate PRs like #455 in the future without changing any actual behaviour.

Dockerfile: split release and dev recipes

---

internal/servegit/serve.go
internal/servegit/serve_test.go

This is a useful use case which allows changing your root by updating a
symlink. Additionally it is convenient. We have to explicitly resolve
the symlink since filepath.Walk does not support resolving symlinks. We
resolve the symlink each time we crawl so the user can update the value
of the symlink at runtime. Note: we still ignore symlinks with the repos
directory. Supporting that would be more complex due to symlink cycles.
Fixes https://github.com/sourcegraph/src-cli/issues/453

servegit: eval symlinks on root

---

internal/output/block.go
internal/output/output.go
internal/output/pending_tty.go
internal/output/progress_tty.go
internal/output/progress_with_status_bars_tty.go

I actually like the locking change here on `Output` as well, regardless of the merits of the cursor handling change.
This seems to improve things a bit on Windows and some, but not all, Linux terminal emulators.

output: hide the cursor when updating

---

CHANGELOG.md
go.mod
go.sum
internal/campaigns/executor.go
internal/campaigns/executor_test.go

This uses https://github.com/sourcegraph/campaignutils/pull/9 to extend the pattern syntax for the `published` field in the `changesetTemplate` to allow addressing specific changesets in a repository by their branch name.
Example:
```yaml
name: branch-addressing
description: Addressing a single changeset by branch name
on:
- repository: github.com/sourcegraph/automation-testing
workspaces:
- rootAtLocationOf: package.json
in: github.com/sourcegraph/automation-testing
steps:
- run: |
echo "We are in $(basename $(pwd))" >> message.txt &&
basename $(pwd)
outputs:
directoryName:
value: ${{ step.stdout }}
changesetTemplate:
title: Branch addressing
body: Addressing a single changeset by branch name
commit:
message: Branch addressing
branch: thorsten/branch-addressing-${{ …
```

Allow addressing changesets by branch

---

CHANGELOG.md
cmd/src/campaigns_common.go
internal/campaigns/bind_workspace.go
internal/campaigns/bind_workspace_test.go
internal/campaigns/campaign_spec.go
internal/campaigns/executor.go
internal/campaigns/executor_test.go
internal/campaigns/graphql/repository.go
internal/campaigns/repo_fetcher.go
internal/campaigns/repo_fetcher_test.go
internal/campaigns/run_steps.go
internal/campaigns/service.go
internal/campaigns/service_test.go
internal/campaigns/volume_workspace.go
internal/campaigns/volume_workspace_test.go
internal/campaigns/workspace.go
internal/exec/expect/expect.go
schema/campaign_spec.schema.json
schema/campaign_spec_stringdata.go

This does two things:
1. When `workspaces` are used in the campaign spec, _only_ an archive of the workspace (including all subdirectories and subworkspaces) is downloaded. That helps a lot with monorepos where it's unfeasible to download the whole repository.
2. When only the workspace is downloaded two files from the root of the repository are additionally downloaded, if they exist: `.gitignore` and `.gitattributes`.
---
The code is by not polished yet, but it works, I added a lot of tests and hope to get a first round of reviews that I can then work off tomorrow.
What's missing:
---
Big questions:
---
Thank you for reviewing.
Yours truly,

Only fetch archive of subdirectories in workspaces

---

CHANGELOG.md
internal/campaigns/repo_fetcher.go

When multiple containers use the same additional files, they could sometimes be deleted before the last container was done using them. Docker bind mount errors were happening then.
This fixes it by taking the workspace path into account for the local file path, making it truly unique between workspace runs.

Fix additional files being deleted prematurely

---

CHANGELOG.md
cmd/src/users_delete.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/17859 by asking the user for confirmation before deleting all users on an instance.

Ask user for confirmation before deleting all users

---

CHANGELOG.md
internal/campaigns/execution_cache.go
internal/campaigns/execution_cache_test.go

This fixes sourcegraph/sourcegraph#17306 by deleting support for old cache files.
The ticket is slightly wrong, since the previous code did already delete
these files, so we don't have to deprecate and then delete support. We
already transitioned to the new cache file format in 3.24 and 3.25 now.
The next release, 3.26, will only read the new cache format.

Deprecate old ExecutionCache file formats

---

CHANGELOG.md
cmd/src/version.go
internal/api/api.go
internal/api/flags.go
internal/campaigns/repo_fetcher.go

This adds an optional flag to disable certificate validation. Given that, I think it should fix https://github.com/sourcegraph/src-cli/issues/463. I don't know how I feel about this, but it seems to work ok:

Add flag to insecurely skip certificate validation

---

CHANGELOG.md
internal/campaigns/service.go

This code went through a few iterations when we were developing it: originally, we only pulled the helper Docker image if volume mode was actually in use, but then we needed additional heuristics to determine when to enable volume mode based on the campaign's Docker images, which created a circular dependency between the Docker images and the workspace Docker image.
However, something changed right at the end of this that I hadn't fully thought through: originally, the workspace creator defines what Docker image(s) it required, but that was simplified into the service itself at some point. Additionally, pulling the helper image became a separate step in `SetDockerImages`, whereas before it was part of the same loop used for pulling campaign images.
The heuristic in …

campaigns: only pull the Docker image in volume mode

---

CHANGELOG.md
docker/campaign-volume-workspace/Dockerfile
internal/campaigns/volume_workspace.go

#478 has the details on what's being fixed here. I also realised that we don't use `curl` any more within the volume workspace itself, so we can reduce the size of the helper image.

campaigns: better handle non-root images in volume mode

---

CHANGELOG.md
cmd/src/login.go
cmd/src/login_test.go

This wasn't respecting api flags.
I also had to update the logic for retrieving the endpoint a bit, since it could have picked up a flag.

Also respect client flags in src login command

---

cmd/src/format.go
cmd/src/search.go
cmd/src/search_alert.go
cmd/src/search_alert_test.go
cmd/src/search_stream.go
cmd/src/search_stream_test.go
cmd/src/testdata/streaming_search_want.txt
internal/api/flags.go
internal/streaming/search.go

Stacked on top of #484 
This adds the flag `-stream` to the `search` sub-command. Searches
submitted with `-stream` are routed to the endpoint `search/stream`
instead of the GraphQL api.
In addition, users can set `-display <int>` to set the display limit.
We will add support for JSON in a follow-up PR.

search: add support for streaming search

---

CHANGELOG.md
internal/batches/graphql/campaigns.go

Well, that was embarrassing. I guess I get a dunce hat instead of a propeller hat for this version.
Fixes #495.

batches: fix batch apply on old Sourcegraph versions

---

internal/batches/batch_spec.go
internal/batches/batch_spec_test.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/16955.
Preview:

More user-friendly error message if batch change name is invalid

---

.goreleaser.yml
CHANGELOG.md

Annoyingly, this passes GoReleaser's check action, but then does nothing silently.
Fixes #501.

goreleaser: correctly structure the docker section

---

README.markdown

Fix broken links for batch changes.
Better document maintenability.

Fix broken link for batch changes docs

---

CHANGELOG.md
cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_preview.go
internal/batches/errors.go
internal/batches/graphql/repository.go
internal/batches/service.go
internal/batches/service_test.go

This implements https://github.com/sourcegraph/sourcegraph/issues/18330 by querying the locations of `.batchignore` files in each repository yielded by the `on` attribute in a batch spec. If locations were found, the repository is ignored.
This can be overwritten by using the `-force-override-ignore` flag.
Example: given my instance has the following repositories:
- `github.com/sourcegraph-testing/zap`
- `github.com/sourcegraph-testing/titan`
- `github.com/sourcegraph-testing/tidb`
- `github.com/sourcegraph-testing/etcd`
- `github.com/sourcegraph-testing/batch-changes-testing-ignore`
And I use the following batch spec:
```yaml
on:
- repositoriesMatchingQuery: repohasfile:README.md repo:sourcegraph-testing
steps:
- run: echo "a horse says 'hello'" >> README.md
```
with …

Filter out repositories with .batchignore at root

---

cmd/src/batch_common.go

Woops, missed this in the last PR. Lead to cache not working.

Set cacheDir in executor.Opts to fix cache

---

cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_preview.go
cmd/src/batch_progress_printer.go
cmd/src/batch_repositories.go
cmd/src/batch_validate.go
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go
internal/batches/service/service.go
internal/batches/workspace/bind_workspace.go
internal/batches/workspace/volume_workspace.go
internal/batches/workspace/workspace.go
internal/batches/workspace/workspace_test.go

This is a follow-up to #511 and #512.
It cleans up the code that's shared between `batch apply` and `previe`
by trying to make the boundaries between the "TUI +
execution"-glue-code, the `service` pkg, the `executor` pkg and the
helpers clearer.
A lot of this is subjective, of course (what does "clearer" even mean,
man), but I think less duplication is Good and less cross-talk between a
trio of components too.

Clean up shared code between `batch apply` and `preview`

---

cmd/src/batch_common.go
internal/batches/service/service.go

I introduced this when re-organizing the code in `batch_common.go`, but
I didn't run into this because I've only developed on Linux since.
On macOS, though, `src` would panic when the
`DockerVolumeWorkspaceCreator` would check the `ImageUIDGUID` on each
step, because `step.image` was nil.
This fixes the issue by making sure that all images are pulled before
inspecting them.
As a requirement to the change it also pulls out the pulling of the
workspace creator image, which I think is actually an improvement
because it makes the code less decoupled.
Guess I should switch between macOS and Linux more often.

Fix macOS panic by pulling images before determining workspace creator

---

cmd/src/batch_common.go

Apparently I lost this flag when cleaning up the code here. So: too much
cleaning, but due to that not enough cleaning.
In practical terms: before this commit and since the regression repo
archives would've been kept around, by default.

Fix regression by setting CleanArchives flag again

---

DEVELOPMENT.md
cmd/src/batch_common.go
internal/batches/debug.go

I don't care about the specifics - filename, build tag, etc. - but I
*need* this. And the reason why I need it is that it's hard to log
something when our TUI is active. Not because of how the TUI is
implemented, but because the whole concept of an updating TUI doesn't
gel with printf-debugging.
And this is perfect for me: I can `tail -f` the log file and then use
`log.Printf` whereever I want.

Set default log to src-cli.debug.log if build tag debug is used

---

internal/batches/executor/executor.go

Since we use a "reference counting" mechanism when checking out archives
we shouldn't bump the ref count if we never execute steps.
Because only after executing the steps do we decrease the ref count and
thus "free" the archive to be cleaned up.
The problem is that if a `Task` has a cache hit then the ref will never
be decreased and the archive never cleaned up.
Edit, just to clarify: it's hard to hit this, since it requires `workspaces` to be defined and `if:` conditions structured in a way that would bust the cache for _one_ of N workspaces that use the same archive.

Only checkout repo archive if steps will be executed

---

cmd/src/batch_common.go
internal/batches/executor/changeset_specs.go
internal/batches/executor/check_cache.go
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go
internal/batches/executor/task.go
internal/batches/executor/task_status.go
internal/batches/repo_fetcher.go
internal/batches/service/service.go

This is based on @eseliger's idea, which was confirmed independently by @courier-new as something worthwhile.
In short: before this change we wouldn't tell users whether we have cached results _and_ we'd only check the check once we start executing a task. The problem with that is that if you have 500 tasks to execute, 480 of which are cached, the UI would tell you "executing 4/500 tasks" and then only speed up once it gets to the cached values.
This PR here pulls the cache-checking out of the task execution and makes it a separate step in the batch spec execution and in the UI:
---
**Note to reviewers:** there is also a lot of other clean-up/refactoring/move-around stuff in here that I either (a) had to do to make this easier or (b) wanted to do after digging more into this and realizing …

Make checking of cache explicit in TUI

---

internal/batches/executor/executor.go
internal/batches/executor/executor_test.go

We didn't return the specs in case of an error, so we would ignore the error, but still have no changeset specs uploaded, which resulted in the generated batch spec in the preview being empty.

Fix skip errors flag

---

cmd/src/batch_progress_printer.go
cmd/src/batch_progress_printer_test.go
internal/batches/executor/coordinator.go
internal/batches/executor/executor.go
internal/batches/executor/task_status.go

This fixes the regression reported in
https://github.com/sourcegraph/sourcegraph/issues/21230 and introduced
by yours truly in
https://github.com/sourcegraph/src-cli/commit/d6c876cd32397ad53f1e5df1a850fcac7076ba3e.
With the introduction of the Coordinator and the explicit steps of
checking-the-cache-for and building-of ChangesetSpecs outside the
executor, the `TaskStatus.ChangesetSpecs` field wasn't set at the time
when `FinishedAt` was set.
The `batchProgressPrinter` assumed, though, that this was the case and
that if `FinishedAt` was set that `len(taskStatus.ChangesetSpecs) == 0`
means "No changes".
This change here fixes the problem by distinguishing between the two
states: finished execution of steps and finished building changeset
specs.
The problem is that it's still a slight …

Distiguishing "finished exec" and "built specs" in TaskStatus

---

cmd/src/version.go

The output of `src version` uses inconsistent capitalization of
"version", and the recommended version can sometimes be a downgrade
compared to what is actually installed. The changes in this PR are to:
- standardize on lower-case `v` in "version"
- add `or later` to output of recommended version
Fixes sourcegraph/sourcegraph#16850

Clean up the `src version` output

---

cmd/src/batch_common.go

Closes [#20470](https://github.com/sourcegraph/sourcegraph/issues/20470).
[Separate PR](https://github.com/sourcegraph/sourcegraph/pull/21317) on sourcegraph/sourcegraph adds a redirect for the old URL.

batches: update troubleshooting link URL

---

CHANGELOG.md
internal/batches/executor/changeset_specs_test.go
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/execution_cache.go
internal/batches/executor/execution_cache_test.go
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go
internal/batches/executor/main_test.go
internal/batches/executor/run_steps.go
internal/batches/executor/task.go
internal/batches/executor/task_builder_test.go
internal/batches/executor/templating_test.go
internal/batches/log/manager.go
internal/batches/log/task_logger.go
internal/batches/mock/logger.go
internal/batches/workspace/bind_workspace.go
internal/batches/workspace/bind_workspace_test.go
internal/batches/workspace/volume_workspace.go
internal/batches/workspace/volume_workspace_test.go
internal/batches/workspace/workspace.go

This adds step-wise caching for the execution of batch specs.
In short, given a batch spec that contains the following
```yaml
on:
- repository: github.com/sourcegraph/automation-testing
- repository: github.com/sourcegraph-testing/mkcert
steps:
- run: echo "this is step 1" >> caching.txt
- run: echo "this is step 2" >> README.md
- run: echo "this is step 3" >> README.md
outputs:
myOutput:
value: "what is up"
- run: echo "this is step 4" >> caching.txt
if: ${{ eq repository.name "github.com/sourcegraph/automation-testing" }}
```
this PR would cause `src` to cache the results _per step and per repository.
In practice, this means that if we would change the batch spec from the above so it would look like this …

Implement step-wise caching for batch spec execution

---

internal/servegit/service.go
internal/servegit/service_test.go

Ensure that if the Content-Encoding of a servegit request is gzip then we read it as a compressed input. git-upload-pack does not accept gzipped input and fails. This is only sometimes gzipped and I'm not sure of the conditions so we can't rely on it being always or never encoded.
This is a port of https://github.com/sourcegraph/sourcegraph/pull/21067
Co-authored-by: @efritz

servegit: decompress input to git-upload-pack

---

internal/batches/executor/executor.go
internal/batches/executor/run_steps.go

This is a tiny follow-up to #540 and removes the TODO that Adam confirmed in his review.
It simplifies things by passing `*Task` directly to `runSteps`.

refactor: Pass *Task directly to runSteps

---

CHANGELOG.md
internal/batches/workspace/volume_workspace.go

See example 19.7 here: https://tldp.org/LDP/abs/html/here-docs.html
TIL that it's possible to turn variable expansion off.

Never expand the inline diff when applying a cached step diff

---

CHANGELOG.md
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go

This was a left-in "debug removal" that I added in https://github.com/sourcegraph/src-cli/commit/348c49a24dc18e6da5a8a231fea52d840ddcc0a3#diff-e7d4e9760b2767b61760170f3620004882b9fa493251c3619f15d68534891e75L142
It broke the UI. I'll release a new version right after merging this.

Fix broken UI by setting FinishedAt again

---

CHANGELOG.md
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go

Forgot to implement this but ran into it myself when debugging a batch spec.
Will do a patch release after this is in.

Clear step caches when -clear-cache is specified

---

DEVELOPMENT.md
README.markdown

doc: improve developer docs

---

.github/workflows/docker.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
docker/batch-change-volume-workspace/push.py

Since a credential rotation, the GitHub Action responsible for pushing the [src-batch-change-volume-workspace][1] has been failing. This action works as expected when used via Docker outside of the GitHub Action infrastructure; I suspect there's an issue with the handling of a particular character in the action-specific entry script.
That said, there's not _much_ reason to pull in a third party action here; the push script already has the required credentials, and the Docker Hub API, while undocumented, is straightforward. I've added the required urllib-foo to make this happen. (I'd normally pull in Python's excellent requests library for this kind of thing, but that means we'd have to start installing dependencies in the GitHub Action that runs this script, and that feels like more …

docker: fix publish workflow

---

go.mod
go.sum
internal/batches/executor/changeset_specs_test.go

The `specWith()` and `taskWith()` helpers inadvertently mutate `defaultChangesetSpec` and `defaultTask` fields, rather than isolating their changes to just the returned spec and task, respectively. Practically speaking, this means that all tests have the same spec and task based on the last element in the `tests` slice, which means that all the test cases end up testing the same, identical thing.
Instead, we must deep copy the spec and task before invoking the mutator function. I've chosen to pull in a third party package (specifically, [copystructure](https://github.com/mitchellh/copystructure)) for this: naïvely using JSON to marshal and unmarshal doesn't work because most of the interesting task fields are excluded when marshalled to JSON.

batches/executor: fix TestCreateChangesetSpecs

---

cmd/src/lsif_upload.go
cmd/src/lsif_upload_flags.go
go.mod
go.sum

As we previously used a different API client as was provided in the src-cli codebase, we did not take into account the `-skip-insecure-verify` flag. This affected a customer as they used self-signed certs.
This PR passes the src-cli configured API client that honours the flag to the LSIF upload function that resides in sg/sg/lib. The only part of the API client that is consumed is the direct pass-through method, [Do(...)](https://sourcegraph.com/github.com/sourcegraph/src-cli@main/-/blob/internal/api/api.go?L147)
Related to https://github.com/sourcegraph/sourcegraph/pull/22399 and will require bumping go.mod here when it is merged.
cc @efritz for :eyes: after PTO

Support -insecure-skip-verify flag for LSIF upload

---

CHANGELOG.md
go.mod
go.sum

This pulls https://github.com/sourcegraph/sourcegraph/pull/22375 across to actually get the output handling fixes into src-cli.

go.sum: upgrade sourcegraph/lib dependency

---

docker/batch-change-volume-workspace/README.md
docker/batch-change-volume-workspace/push.py

We used to update the Docker Hub description for
https://hub.docker.com/r/sourcegraph/src-batch-change-volume-workspace
on release, but doing so reliably has proven to be difficult, as Docker
Hub doesn't provide a reliable API to do this. When it fails, the entire
release shows up as red, which is obviously not ideal!
Since this description rarely changes, and the pushes themselves are
reliable, this removes the description update and makes it a manual
process.

docker: remove description updates when publishing a release

---

CHANGELOG.md
cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_preview.go
cmd/src/batch_text_logging.go

This adds a `-text-only` flag to `src batch [apply|preview]` that is **for internal use only**.
It's a highly-experimental feature that should not be used if you're not sure about what you're doing.

For internal use only: add a -text-only flag to `src batch [apply|preview]`

---

go.mod
go.sum
internal/batches/executor/changeset_specs.go
internal/batches/executor/changeset_specs_test.go

See https://github.com/sourcegraph/batch-change-utils/pull/12 for more context.
Note to self: this needs a mechanical `go get` update once that PR is merged before _this_ PR can be merged.

batches: correctly fallback to nil for unmatched published fields

---

CHANGELOG.md
internal/batches/service/service.go
internal/batches/service/service_test.go

Using `count:all` would have added a second `count:999999` which breaks the search query.

Allow using count:all in repo query

---

CHANGELOG.md
internal/batches/executor/executor_test.go
internal/batches/executor/run_steps.go
internal/batches/executor/templating.go
internal/batches/executor/templating_test.go
internal/batches/git/changes.go
internal/batches/git/changes_test.go

This PR fixes a bug in the step-wise caching logic that @eseliger and I ran into last week.
When no cached result for the *complete* task was found, but a cached result for a single step and that step was the only left to execute then an empty diff was returned.
1. Execute a batch spec with the following steps
```yaml
steps:
- run: echo "this is step 1" >> README.txt
- run: echo "this is step 2" >> README.md
```
the complete results and the results for each step are now cached.
2. Update the batch spec and re-execute:
```yaml
steps:
- run: echo "this is step 1" >> README.txt
```
This will produce an empty diff because the `Coordinator` did not find a cached result for the complete task/batch spec, but for the first step. …

Fix empty diff being returned when single *cached* step had to be executed

---

cmd/src/search_stream.go
internal/streaming/client.go
internal/streaming/events.go

Paired with  https://github.com/sourcegraph/sourcegraph/pull/22996
I assume the steps now are:
1) Release this as a new version (once the [File -> Content PR](https://github.com/sourcegraph/src-cli/pull/569) is merged as well)
2) Bump the [minimum src version](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/src-cli/consts.go?subtree=true) in https://github.com/sourcegraph/sourcegraph/pull/22996
3) Merge https://github.com/sourcegraph/sourcegraph/pull/22996
I will not merge either of these PRs until after the version cut, because I don't want to get them partially applied.

add EventPathMatch to the streaming API types

---

CHANGELOG.md
internal/batches/ui/json_lines.go

The code that's in here I had before, but somehow lost when restructuring things. Now the message works again and can be used as a trigger for the web UI to show a different "executing tasks" UI.

Fix printing of EXECUTING_TASKS start message

---

internal/batches/ui/tui.go

While doing a `src batch` run I noticed there was a typo in the output. Traced that to this line of code. Please accept the fix.
Thanks!~

Fix typo in message printed during batch runs

---

CHANGELOG.md
cmd/src/batch_validate.go

When creating the `Service` instance, `src batch validate` failed to request or initialise the Sourcegraph feature flags based on the Sourcegraph version in use. As a result, only baseline features were enabled when parsing and validating batch specs.
Fixes #576.

batches: fix feature detection in `src batch validate`

---

cmd/src/batch_new.go
internal/batches/service/service.go

Now that this property isn't required anymore, we can get rid of that part. Honors the feature flag for optional publish values.
Closes https://github.com/sourcegraph/sourcegraph/issues/22180

Remove published: false from template for batch new

---

cmd/src/test.sh
internal/batches/executor/testdata/dummydocker/docker

some *nix systems don't have `/bin/bash`. `/usr/bin/env` is more
portable. I came accross this issue while running the tests on nixos.

all: use /usr/bin/env bash

---

CHANGELOG.md
internal/batches/ui/json_lines.go

@eseliger ran into this yesterday. Easy to reproduce: when all tasks are cached then none will need to be re-executed and `tasks` in the log message would be `null`.

Fix null in JSON log lines output by removing nil slice

---

internal/codeintel/gitutil_test.go

The test `TestInferRepo` unnecesarily depends on the root being a git
repository. This change updates `TestInferRepo` to create a fresh git
repo in a temporary dir.
Why?
I want to add src-cli to the nixos package repository. During the build
stage, nixos downloads a tar of the repo. The tar, however, is not a git
repo and thus `TestInferRepo` fails.

test: don't rely on root being a git repo

---

internal/batches/service/build_tasks.go
internal/batches/service/service.go
internal/batches/service/workspaces.go
internal/batches/service/workspaces_test.go

This makes it easier to map 1 repo workspace to 1 task, useful in SSBC when we split per workspace.

refactor: One RepoWorkspace per workspace

---

cmd/src/batch_common.go
internal/batches/service/build_tasks.go
internal/batches/service/service.go
internal/batches/service/workspaces.go
internal/batches/service/workspaces_test.go

Cleanup code after refactoring of workspaces/steps

---

go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor.go
internal/batches/executor/run_steps.go
internal/batches/ui/interval_writer.go
internal/batches/ui/interval_writer_test.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go

This is part of https://github.com/sourcegraph/sourcegraph/issues/23496 and adds the logging of STDOUT/STDERR of steps to the `-text-only` output. Please see the comment I left for more info on how the interface could be improved/extended.
Also: turns out I don't need the `process.Logger` that was extracted in https://github.com/sourcegraph/sourcegraph/pull/24545 and instead what's needed is the `IntervalLogger` here that flushes the captured output with a delay (so we don't create a new huge JSON message for every line)

text-only output: log stdout/stderr of steps

---

internal/batches/service/service.go

Rev and repo name were shifted, this probably returned no results at all times. I introduced that earlier, but it hasn't been released so far.

Fix DirectoriesContainingFile query

---

internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor.go
internal/batches/executor/run_steps.go
internal/batches/executor/ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go

This is a follow-up to https://github.com/sourcegraph/src-cli/pull/597 and splits up the existing interface into two.
That allows us to remove all formatting from `runSteps` and `executeSingleStep` and also provide more information for the JSON interface (e.g. when a step is finished).
**Note**: the `OPERATION` and `STATUS` fields in the `logEvents` don't make a lot of sense. Happy to change everything there.

executor UI: extract StepsExecutionUI from TaskExecutionUI and implement it in TUI and JSON

---

internal/batches/executor/run_steps.go

This might've been the cause for the flaky test we saw (example failure [here](https://github.com/sourcegraph/src-cli/runs/3507335874)).
The docs say that `cmd.Run()` in combination with `StdoutPipe`/`StderrPipe` is wrong:
> `Wait` will close the pipe after seeing the command exit, so most callers
> need not close the pipe themselves. It is thus incorrect to call `Wait`
> before all reads from the pipe have completed. For the same reason, it
> is incorrect to call `Run` when using `StdoutPipe`. See the example for
> idiomatic usage.
See: https://pkg.go.dev/os/exec#example-Cmd.StdoutPipe

Start/Wait on exec.Cmd when using pipes

---

internal/batches/service/build_tasks.go
internal/batches/service/service.go
internal/batches/service/service_test.go

I don't see where this could happen. We get the path from the search API and that returns "" for the root. Can we remove this special handling?

Move fallback from `.` to `""` in workspace path into workspace finder

---

cmd/src/batch_common.go
go.mod
go.sum
internal/batches/service/service.go
internal/batches/ui/exec_ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/tui.go

Next step I will move the step output definition into the shared lib, so we can use it server-side for parsing.
This requires a server-side change which I am going to publish when we release SRC CLI so we have a version match in the executors, too.

Streamline and improve JSON UI

---

CHANGELOG.md
cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_exec.go
cmd/src/batch_preview.go
go.mod
go.sum
internal/batches/ui/tui.go

This adds the for-internal-use-only `src batch exec` command that will be used by server-side batch changes to execute a batch spec in specific workspaces on different machines, concurrently.
**Note:** the vast majority of the added code you see here is copy&pasted from `batch_common.go`. I really _don't_ want to add more conditionals to the huge function in there though, so I created a new one. Yes, there's duplication, but it's so much easier to understand and to maintain. And we'll likely make a lot of changes to this new function here anyway, so effort to generalize and DRY this code will probably be wasted.
Given the following input file, `input.json`
```json
{
"rawSpec": "\nname: text-only-output-4\ndescription: Just a test campaign spec to test text only output\n\non:\n  - …
```

For internal use only: add `src batches exec` command

---

cmd/src/batch_common.go
cmd/src/batch_exec.go
cmd/src/batch_validate.go
internal/batches/ui/tui.go

Before this 'src batch validate' would...
1. not print an error if talking to the Sourcegraph instance failed
2. not unpack multi errors correctly and printing all of them
This fixes both issues.

Fix displaying of errors in 'src batch validate'

---

internal/batches/executor/run_steps.go
internal/batches/executor/ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go

When determining workspaces, we determine the env, too. The values are preliminary though, as they might depend on what's set in the environment of src-cli or use template variables that aren't known at time of workspace determination. This logs the final set of env vars as used for the step.

ssbc: Log final env when resolved

---

cmd/src/batch_common.go
cmd/src/batch_exec.go
go.mod
go.sum
internal/batches/executor/coordinator_test.go
internal/batches/executor/run_steps.go
internal/batches/executor/ui.go
internal/batches/ui/exec_ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go
internal/batches/ui/tui.go

Required for new SSBC step resolvers to have all data needed.
<details>
<summary>Successful run</summary>
```
{"operation":"PARSING_BATCH_SPEC","timestamp":"2021-09-22T14:32:05.623Z","status":"STARTED"}
{"operation":"PARSING_BATCH_SPEC","timestamp":"2021-09-22T14:32:05.624Z","status":"SUCCESS"}
{"operation":"PREPARING_DOCKER_IMAGES","timestamp":"2021-09-22T14:32:05.624Z","status":"STARTED"}
{"operation":"PREPARING_DOCKER_IMAGES","timestamp":"2021-09-22T14:32:05.624Z","status":"PROGRESS","metadata":{"done":0,"total":1}}
{"operation":"PREPARING_DOCKER_IMAGES","timestamp":"2021-09-22T14:32:05.792Z","status":"PROGRESS","metadata":{"done":1,"total":1}}
{"operation":"PREPARING_DOCKER_IMAGES","timestamp":"2021-09-22T14:32:05.792Z","status":"SUCCESS"} …
```

Cleanup and complete json logs a bit

---

CHANGELOG.md
README.markdown
internal/api/api.go
internal/api/flags.go

This PR unconditionally changes the User-Agent to `src-cli`, rather than the default Go user-agent, and adds the OS and architecture to src for support and product purposes by default. This can be disabled via an environment variable and/or flag, and is documented accordingly.
Closes sourcegraph/sourcegraph#15769.

api: add User-Agent header

---

cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_exec.go
cmd/src/batch_preview.go
go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/execution_cache.go
internal/batches/ui/json_lines.go

This is part of https://github.com/sourcegraph/sourcegraph/issues/26929
and requires https://github.com/sourcegraph/sourcegraph/pull/27061 on
the `sourcegraph/sourcegraph` side.
It adds a `JSONLinesCache` that writes cache entries to stdout. It's
used when executing `src batch exec`, which results in cache entries
being transfered to the Sourcegraph server via the executor.

Add JSONLinesCache to write cache entries to stdout

---

cmd/src/batch_exec.go
internal/batches/executor/coordinator.go

This is part of https://github.com/sourcegraph/sourcegraph/issues/26929
and simplifies the caching-related logic in `src batch exec` to only
what's needed: checking for per-step cache results.
Since server-side batch changes use server-side caching for changeset
specs we don't need to check for changeset specs.

Simplify caching logic in 'src batch exec'

---

internal/servegit/serve.go
internal/servegit/serve_test.go

This is in response to my own issue (#634) where I was asking for support for serving bare repositories from a directory.
This PR has a couple of changes. Some of them can be seen as a refactoring of sorts. The comments in the original implementation were a bit misleading as they appeared to be the other way around (compared to what the tests wanted). I took the liberty to rewrite them a bit. All of the original tests still pass. I've added one case where a bare repository is created (by suffixing the name of a repo with `.bare`) which seems to work. I am not happy about the repository name suffix hack that I had to add but it also doesn't seem like it is worth the effort to refactor the entire test machinery just because of this.
I am open for feedback on this.
cc @mrnugget & …

Support serving bare repositories

---

internal/batches/executor/run_steps.go

Steps are 1-indexed in our JSON UI, but we forgot to add the obligatory +1 here that we do everywhere else.

Fix off-by-one error in JSON UI for skipping steps

---

CHANGELOG.md
internal/batches/workspace/workspace.go

Tested basic "hello world" batch spec with volume mount mode (both setting the workspace flag and on auto with the new default condition) and didn't see any issues with the execution or the diffs produced. The new condition will default to volume mode for Intel and M1 Macs and keep bind mode as the default for anything else. I updated some comments in the area to capture the discussion @LawnGnome and I had about eventually moving to volume mode as the default for everyone.
Closes https://github.com/sourcegraph/sourcegraph/issues/27549

batches: support volume mode on Apple Silicon

---

CHANGELOG.md
internal/batches/log/task_logger.go

Fixes https://github.com/sourcegraph/sourcegraph/issues/27860
Output after this change:
```
2021-11-26T15:13:58.653891+01:00 [Step 1] run: "echo \"I am the real Doctor Doom!\";\necho \"Doom?\";\ni=1\nwhile [ $i -le 3 ]\ndo\n  echo \"Doom!\"\n  i=$(($i+1))\ndone\necho \"I am the one true doom!\";\necho \"Doom was here!\" >> message.txt && cat message.txt;\n", container: "alpine:3"
2021-11-26T15:13:58.654013+01:00 [Step 1] full command: "docker run --rm --init --cidfile /tmp/github.com-sourcegraph-src-cli-e1b02cba1a569231092d19edae4701aca205091a-container-id3858813705 --workdir /work --mount type=bind,source=/tmp/3671410092,target=/tmp/tmp.AGjGdD,ro --user 0:0 --mount type=volume,source=1b39a55789ee5b072a7014e132d8bc9b410049d7b5ceb83e1a0b43c49b5e882e,target=/work --entrypoint /bin/sh -- …
```

Fix log lines being intertwined by newlines

---

CHANGELOG.md
go.mod
go.sum

As promised, this includes a changelog entry.

go.mod: pull in sourcegraph/sourcegraph#28240 fix

---

internal/batches/ui/task_exec_tui.go

Before this would print "Preparing 1", now it prints "Preparing step 1".

Improve TUI label for improving step

---

cmd/src/batch_common.go
cmd/src/batch_exec.go
go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor_test.go
internal/batches/executor/run_steps.go
internal/batches/executor/ui.go
internal/batches/service/service.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go

This PR changes src exec's behavior to not upload changeset specs anymore. They aren't required anymore. 
See main PR for more details: https://github.com/sourcegraph/sourcegraph/pull/28158

Build changeset specs server side

---

CHANGELOG.md
cmd/src/validate.go

Follow-up to this problem reported on [Slack](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1640031669019000).
Due to https://github.com/sourcegraph/sourcegraph/pull/28572, the CSRF headers were removed and due to a bug in the error checking code, [triggers a panic](https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/24470).

Remove CSRF tokens fetching code

---

internal/streaming/search.go

Relates to https://github.com/sourcegraph/sourcegraph/issues/29399
This updates stream search to call .api/search/stream instead of
/search/stream. We plan to retire /search/stream as soon as all clients
have been migrated.

search: use .api/search/stream

---

cmd/src/lsif_upload.go
go.mod
go.sum

This includes the changes made in https://github.com/sourcegraph/sourcegraph/pull/29538 in-particular, which makes it more obvious/actionable when retries and errors occur.

lsif upload: Update lib for QoL improvements

---

CHANGELOG.md
internal/api/version_check.go
internal/batches/features.go

This is a partial fix for the issue Malo was running into when trying to execute a batch spec with src-cli on demo.sourcegraph.com despite having `user.name` and `user.email` set in his git config:
```
❌ Error:
{
"message": "3 errors occurred:\n\t* Must validate one and only one schema (oneOf)\n\t* commits.0: authorName is required\n\t* commits.0: authorEmail is required\n\n",
"path": [
"createChangesetSpec"
]
}
```
I thought, and we say in the docs, that
> The commits created from your spec will use the git config values for `user.name` and `user.email` from your local environment
but I couldn't actually find if/how this happening in the code. In `BuildChangesetSpecs`, we explicitly [only check the changeset template from the input …

batches: encourage semver that prerelease versions are newer

---

internal/api/version_check.go
internal/api/version_check_test.go

Follow up to https://github.com/sourcegraph/sourcegraph/pull/29654, the version string for Sourcegraph in certain pre-release environments now will feature the 12-character abbreviated commit hash at the end.
See https://sourcegraph.slack.com/archives/C01N83PS4TU/p1642013850061100 for more.
Fixes [29618](https://github.com/sourcegraph/sourcegraph/issues/29618).

batches: match on abbreviated commit hash in version

---

cmd/src/validate.go

Help validating instance by performing the following checks ( from a custom json / yaml file or will run defualt values if none are specified): - Add a code host - clone a repo - make a search for the repo - make an unindexed search on the repo. *  fixes : the SleepBetweenTriesSeconds field not being read

WIP: Script for Validating Sourcegraph Instance

---

cmd/src/batch_common.go

It's essentially just a typo fixed here.
Without this fix then repo errors when running things like `src batch preview` are just ignored, and the cli returns with exit code 0 without any error messages without uploading changesets for any successful repo (which is intended, you need to set `-skip-errors` for it to do that).
See output below for examples.
Took me a couple of days to figure out what was the problem. I could see that there were errors due to `Executing... (1/1, 1 errored)` but since exit code was 0 and no errors were printed I assumed that src by default ignores repo errors. Which it does not.
Current main branch:
```
$ src batch preview -f batch.yml
✅ Parsing batch spec
✅ Resolving namespace
✅ Preparing container images …
```

Fixed issue where errors were thrown away

---

CHANGELOG.md
cmd/src/batch_apply.go
cmd/src/batch_common.go
cmd/src/batch_exec.go
cmd/src/batch_preview.go
cmd/src/batch_repositories.go
cmd/src/batch_validate.go
go.mod
go.sum
internal/batches/ui/tty.go

New behaviour (assuming `COMMAND` is any command that accepted `-f`, including `apply`, `preview`, `repos`, or `validate`):
* `src batch COMMAND` **on a TTY**: will wait for 250ms in case there's input on stdin; otherwise errors
* `src batch COMMAND` with a file redirected in: waits indefinitely for input
* `src batch COMMAND -f -`: waits indefinitely for input
* `src batch COMMAND FILE`: reads from `FILE`; equivalent to `src batch COMMAND -f FILE`
* `src batch COMMAND -f FILE`: works as before
In summary, this shouldn't break backward compatibility in any case except for the user _slowly_ typing in a batch spec on stdin.
Fixes #680.

batches: make `-f` optional

---

CHANGELOG.md
internal/batches/service/service.go

This PR is in response to https://github.com/sourcegraph/sourcegraph/issues/28252 and does two things:
- ~Lessens the arbitrarily large default count applied to the batch spec `repositoriesMatchingQuery` from 999999 to 99999, which is less likely to cause timeouts.~ Decided not to proceed with this change since we haven't heard of actual enterprise customers running into timeouts yet and this is expected to become a non-issue once we actually use `count: all`.
- Requests BC-specific information from the version GraphQL query so that it produces an error on dotcom or in an environment where batch changes is not available. This has the effect that `src preview|apply` will fail right away on the first thing it does, which is the version check, as opposed to much later after execution …

batches: fail earlier on dotcom

---

internal/batches/service/service.go

This was spotted by @eseliger in the review for #647 — if `total < parallelism`, there's no real need to spawn extra goroutines, so let's not.

batches: use the minimum possible goroutines to fetch images

---

CHANGELOG.md
cmd/src/colors.go
cmd/src/search.go
cmd/src/search_alert_test.go
cmd/src/search_stream.go
cmd/src/search_test.go
go.mod
go.sum
internal/api/version_check.go
internal/batches/service/service.go

I did a quick `src search`, and everything still looks (a) normal, and (b) garishly coloured, so I think we're good.

go.mod: use grafana/regexp, matching sourcegraph/sourcegraph#30948

---

CHANGELOG.md
cmd/src/batch_apply.go

This code should have been the same in `src batch preview` and `src batch apply`, but apparently wasn't. My bad, sorry.

batches: fix `src batch apply -f`

---

cmd/src/batch_remote.go

I obviously missed this when I removed the extra level of commands in the new command structure.

batches: fix incorrect help text

---

go.mod

This caused the release to fail. (Side note: why on earth doesn't Go do this for you when you run `go get` as suggested?)

go.mod: run tidy

---

cmd/src/main_test.go
internal/batches/executor/execution_cache_test.go
internal/batches/executor/executor_test.go
internal/batches/repozip/fetcher_test.go
internal/batches/workspace/bind_workspace_nonwin_test.go
internal/batches/workspace/bind_workspace_test.go
internal/servegit/serve_test.go

A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir

test: use `T.TempDir` to create temporary test directory

---

internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go
internal/batches/executor/run_steps.go

We adjusted the test suite to ensure that tasks are cached after execution of all steps, but the steps are cached immediately the individual execution is done.
We also tested this change on the UI by taking the following steps:
- Create a batch spec that'll fail at a particular step
```yaml
name: testerr
description: Add Hello World to READMEs
on:
- repositoriesMatchingQuery: file:README.md count:100
steps:
- run: echo Hello World 123 | tee -a $(find -name README.md)
container: ubuntu:18.04
- run: exit 1
container: ubuntu:18.04
changesetTemplate:
title: Hello World
body: My first batch change!
branch: hello-world # Push the commit to this branch.
commit:
message: Append Hello World to all README.md files
```
- Ensure it fails, then retry the batch spec run and checking the previous …

Cache step results while steps are executing instead of caching all of them at the end

---

CHANGELOG.md
cmd/src/main.go

Fixes https://github.com/sourcegraph/sourcegraph/issues/32450 and adds a bit more!
* Added `login` command to the list
* Noticed list was not alphabetized so went a step further and re-ordered the commands
* Confirmed changes in src-cli dev environment look visually correct (use spaces versus tabs 🙃 )

add login into command list & alphabetize 

---

CHANGELOG.md
cmd/src/extensions_copy.go
cmd/src/extensions_publish.go
cmd/src/extensions_publish_test.go

Closes #717. 
- Update `updatePropertyInManifest` to remove property when value is an empty string.
- Remove `url` property from manifest before publishing to private registry.
This is a backwards-compatible change, so can it be part of a [patch release](https://github.com/sourcegraph/src-cli/blob/main/DEVELOPMENT.md#releasing)? And is the changelog entry unnecessary in this case then?
- Added a test case for removing properties from an extension manifest.
- Built with `go install` and tested `src ext copy` to confirm that the command still works and that `url ` is no longer included in the manifest.

extensions: remove url from copied manifest

---

cmd/src/search.go

This came out of https://sourcegraph.slack.com/archives/C022SPMNR0W/p1648748082874949.
N/A; help change only.

search: add a tip about negated searches

---

cmd/src/lsif_upload.go

Was missing this new option in help text.
N/A.

lsif upload: Add -gitlab-token to help text

---

CHANGELOG.md
internal/batches/features.go
internal/batches/service/service.go

Part of sourcegraph/sourcegraph#24199.
Testing against sourcegraph/sourcegraph#32826.

Add Bitbucket Cloud to the supported list

---

cmd/src/batch_common.go
cmd/src/batch_remote.go
internal/batches/service/service.go

Run `src batch remote -f comby-go-refactor.batch.yml`
comby-go-refactor.batch.yml
```yaml
name: comby-go-fmt
description: Run `comby` and `go fmt`
on:
- repositoriesMatchingQuery: lang:go fmt.Sprintf("%d", :[v]) patterntype:structural
steps:
- run: comby -in-place 'fmt.Sprintf("%d", :[v])' 'strconv.Itoa(:[v])' ${{ join repository.search_result_paths " " }}
container: comby/comby
- run: goimports -w ${{ join previous_step.modified_files " " }}
container: unibeautify/goimports
changesetTemplate:
title: Replacing fmt.Sprintf with strconv.Itoa
body: This campiagn replaces `fmt.Sprintf` with `strconv.Itoa`
branch: batch-changes/comby-go-fmt # Push the commit to this branch.
commit:
message: Replacing fmt.Sprintf with strconv.Iota
```
The result is an execution URL that doesn't 404.
Closes …

Fix Execution URL when using `src batch remote`

---

cmd/src/lsif_upload.go

Fixes #727.
Ran by hand:
```
$ src lsif upload
💡 Inferred arguments
repo: github.com/sourcegraph/lsif-go
commit: cde8136abd91c0a3bce9f5d2755bc006a2caaafb
root:
file: ./dump.lsif
indexer: lsif-go
indexerVersion: dev
✅ Index compressed
💡 Indexed compressed (6.65MB -> 1.06MB).
❌ Failed to upload index file
unauthorized upload
This Sourcegraph instance has enforced auth for LSIF uploads.
BLAH BLAH TEXT CHANGED SINCE I OPENED THE PR
See https://docs.sourcegraph.com/cli/references/lsif/upload.
```

lsif upload: Make better unauthorized error messages

---

cmd/src/lsif_upload.go
cmd/src/lsif_upload_flags.go
cmd/src/lsif_upload_flags_test.go
go.mod
go.sum

Running `src lsif upload` now converts LSIF Typed into LSIF Graph in the
following scenarios:
- When the provided `-file` flag matches the file extension ".lsif-typed"
- When the provided `-file` flag points to a non-existent file, while
the sibling `*.lsif-typed` file exists.
Fixes https://github.com/sourcegraph/sourcegraph/issues/27405
Manually tested the command locally.
```
❯ ~/dev/sourcegraph/src-cli/src lsif upload
ℹ️  Converting ./dump.lsif-typed into ./dump.lsif
💡 Inferred arguments
repo: github.com/sourcegraph/sourcegraph
commit: 91976dc8c72ce24876c10fa9fa1bd40a5f00e557
root:
file: dump.lsif
...
❯ ~/dev/sourcegraph/src-cli/src lsif upload -file dump.lsif-typed
ℹ️  Converting dump.lsif-typed into dump.lsif
💡 Inferred arguments
repo: github.com/sourcegraph/sourcegraph
commit: …
```

Add support for LSIF Typed

---

cmd/src/lsif_upload_flags.go

Previously, the command `src lsif upload -no-progress` failed with a
nil panic when using LSIF Typed. I was tempted to refactor the code
so that `output` cannot be nil but decided not to in order to keep the
diff small and focused on fixing the panic.
Manually ran `src lsif upload -no-progress` and see it not panic.

Handle nil output when writing progress message

---

cmd/src/lsif_upload_flags.go

Otherwise, this TODO will end up in the Sourcegraph docs.
~The text is based on the old help text which mentioned "with read and write repository scope."~
@efritz locally tested this, `read_api` works.

Remove TODO from flag docs

---

.tool-versions

Tested `go` compilation and test running works locally again. Not a change to the shipped binary.

Bump golang in asdf to 1.18

---

cmd/src/debug_compose.go
cmd/src/debug_kube.go
cmd/src/debug_server.go

Following up from additional comments in #731 (some were hidden by the long timeline in the github view pre merge, and @DaedalusG and I forgot to address these in our 1-1).
N/A.

chore: Follow up to #731

---

CHANGELOG.md
Dockerfile
Dockerfile.release
README.markdown
cmd/src/code_intel.go
cmd/src/code_intel_upload.go
cmd/src/code_intel_upload_flags.go
cmd/src/code_intel_upload_flags_test.go
cmd/src/lsif.go
cmd/src/main.go

Replaces #745. After discussing with Olaf and TJ, it was decided that
adding other commands would be easier if we had the in-between
command. We will add another alias depending on what Code Intel
is rebranded to. 😐
Updated existing tests. Ran `src -h`, `src code-intel -h` and `src code-intel upload -h` manually.

Add src code-intel alias for src lsif

---

CHANGELOG.md

Forgot to mention this earlier when I added support in #742.
n/a

changelog: Add note about SCIP support in 3.40.0.

---

go.mod
go.sum

The PR we want to include https://github.com/sourcegraph/scip/pull/27
See the CI go green. We already tested the upstream bugfix.

Bump SCIP version to include bugfix for textDocument/implementations

---

CHANGELOG.md

changelog: Reference code-intel subcommand instead of lsif.

---

.github/workflows/goreleaser.yml
CHANGELOG.md
npm-distribution/package.json

The last `npm publish` step failed with an authorization error
https://github.com/sourcegraph/src-cli/runs/6707002077?check_suite_focus=true
```
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
29
```
Our current hypothesis is that this change fixes the issue.

Use `setup-node` GitHub Actions step before running `npm publish`.

---

.github/workflows/goreleaser.yml
DEVELOPMENT.md
npm-distribution/package.json
release.sh

Previously, you had to manually open a PR to bump up the version in package.json.
Now, the version is automatically bumped during the release pipeline.
Cut a new release and see if it works.

Simplify npm package release by setting the version

---

.github/workflows/goreleaser.yml

The last npm release job failed with "error Invalid version supplied."
because the inferred version was "refs/tags/3.40.6".
Run the release job and see it succeed.

Fix the regexp to extract the version from git refs

---

CHANGELOG.md

I added sections for the other patch releases just so nobody is confused.
I miss being able to just push changes to `CHANGELOG.md`.
N/A

changelog: update for 3.40.8

---

internal/batches/executor/run_steps.go
internal/batches/workspace/bind_workspace.go
internal/batches/workspace/git.go
internal/batches/workspace/volume_workspace.go

A user reported this, we store execution step results in the cache also when no diff was generated (rightfully), but then we should only apply the patch when there is actually anything to do.
Also, I initially couldn't reproduce this locally because we swallowed this error in volume mode. It would only happen in bind mode.
Closes https://github.com/sourcegraph/src-cli/issues/755
Verified this does properly fail in volume mode now, too and don't fail anymore at all.

Only apply cache result progress if resulted in diff

---

CHANGELOG.md

Rolling out the new fixes to executors, so need a tagged version.
Docs change.

Prepare changelog for 3.40.10

---

internal/batches/workspace/git.go

We parse lots of the things that git outputs, so having stderr randonly interfere with the output breaks that parsing. Since we can still get stderr from the exiterror, I don't think this is a regression at all in debuggability. This was found on k8s where parsing the patch would fail on a particular repo. Turns out git logged a warning.
Verified the patch can now be parsed.

batches: Don't let stderr clutter git output

---

CHANGELOG.md
cmd/src/batch_common.go
cmd/src/batch_exec.go
internal/batches/docker/context.go
internal/batches/docker/image.go
internal/batches/docker/image_test.go
internal/batches/docker/info.go
internal/batches/docker/info_test.go
internal/exec/expect/expect.go

This PR changes the default parallelism of `src batch preview|apply` runs to be based on the CPU cores reported by `docker info`.
Practically, this means that Docker Desktop users will now have their parallelism based on the VM Docker runs within, not their host machine. The trade off here is that Docker Desktop users will likely have their default parallelism cut significantly, but this is also likely to make issues caused by the Docker VM having its resources exhausted considerably less likely.
* I've migrated the previous `docker version` preflight to use `docker info` instead, which means we can get the CPU count and preflight Docker at the same time.
* Since `docker info` should always be quick, this reuses the same timeout behaviour as #783, which has been renamed from being `image …

batches: use Docker CPU count as default parallelism, not GOMAXPROCS

---

CHANGELOG.md
cmd/src/batch_remote.go
internal/batches/service/remote.go
internal/batches/ui/tui.go

Closes #780 
* Create a server-side batch change with the command `src batch remote`
* When the command is done, the batch change should be accessible via the execution link outputted in the terminal

batches: upsert batch change when running `src batch remote

---

CHANGELOG.md
cmd/src/batch_common.go
cmd/src/batch_exec.go
go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor.go
internal/batches/executor/run_steps.go
internal/batches/executor/task.go
internal/batches/executor/task_test.go

Closes [#37216](https://github.com/sourcegraph/sourcegraph/issues/37216).
* Removed the cache checks to enable caching for `mount`
* Renamed `AllowMountPaths` to `IsRemote` for usage in the caching (enables caching for filesystem only)
Go Unit tests and manual testing. See [#37363](https://github.com/sourcegraph/sourcegraph/pull/37363)

batches: Cache filesystem mount

---

AUTH_PROXY.md
CHANGELOG.md
cmd/src/headers.go
cmd/src/headers_test.go
cmd/src/login.go
cmd/src/login_test.go
cmd/src/main.go
cmd/src/main_test.go

* Added Tests
* Tested on the following shell
Closes #749

batches: add SRC_HEADERS for passing multiple custom headers

---

CHANGELOG.md
cmd/src/batch_common.go
cmd/src/batch_remote.go
cmd/src/batch_repositories.go
cmd/src/batch_validate.go

This is essentially a copy-paste implementation of the ideas presented
in this comment here: https://github.com/golang/go/issues/20280#issuecomment-655588450
It fixes #775 and helps with the issue described in https://github.com/sourcegraph/src-cli/pull/793#issuecomment-1163310725. Not sure if it has unintended side-effects.
- Manually tested **only** the `src batch preview -f -` case, not the other cases.

Cancel reading from stdin on Ctrl-C

---

cmd/src/batch_exec.go
go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/execution_cache.go
internal/batches/executor/execution_cache_test.go
internal/batches/executor/executor.go
internal/batches/executor/executor_test.go
internal/batches/executor/run_steps.go
internal/batches/executor/task.go
internal/batches/executor/testdata/dummydocker/docker
internal/batches/executor/ui.go
internal/batches/service/service.go
internal/batches/service/service_test.go
internal/batches/ui/json_lines.go
internal/batches/ui/task_exec_tui.go
internal/batches/ui/task_exec_tui_test.go
internal/batches/workspace/bind_workspace.go
internal/batches/workspace/volume_workspace.go
internal/batches/workspace/volume_workspace_test.go
internal/batches/workspace/workspace.go

This PR cleans up the caching mess that I left behind after the refactors for SSBC to get rid of execution results. We now finally don't have a distinction between the two at all. There are simply step results and if the step is the last step to execute, we are done and build the changeset specs from it. 
Additionally, we save a few passes to parse git diffs and such, which is always nice. 
Accompanied by https://github.com/sourcegraph/sourcegraph/pull/38311
Rely on test suite which is (except renames and some caching number tweaks) untouched and manually verified everything still works.

batches: Refactor caching to get rid of execution cache results altogether

---

cmd/src/code_intel_upload.go

IDs returned by the backend do not wrap the upload ID number in quotes before base64 encoding. This PR updates src-cli to do the same. 
This was interrupting my QA updating :miffed:
Compared IDs returned by the backend with what src-cli was returning

remove quotes from upload ID URL

---

CHANGELOG.md
cmd/src/batch_common.go

That's what you get for restructuring. Also thank you go for allowing shadowing so silently :upside_down_face:
Verified manually workspaces are not empty again.

Fix workspace resolution for non-server-side

---

CHANGELOG.md
cmd/src/batch_common.go
internal/batches/service/build_tasks.go
internal/batches/service/service.go
internal/batches/service/service_test.go

The error was the global error and wasn't unset ever, so the execution would go on and eventually it fails with that error in the end.
Also fixes a swallowed error for clear cache.
Verified the error is no longer kept.

Don't keep unsupported/ignored repos error for server-side resolution

---

CHANGELOG.md
cmd/src/batch_common.go
internal/batches/docker/info.go
internal/batches/docker/info_test.go

If the default temporary directory is in use _and_ Docker Desktop for Linux is the default Docker context, this changes the temporary directory to be one under `~/.cache/sourcegraph/batch-tmp` instead.
Fixes #754.
Tested manually in both workspace modes.

batches: fix Docker Desktop for Linux handling

---

cmd/src/orgs_create.go

running `src orgs create -name X` was failing with
```
GraphQL errors: {
"locations": [
{
"column": 3,
"line": 5
}
],
"message": "Cannot query field \"createOrg\" on type \"Mutation\". Did you mean \"createUser\"?"
}
```
the mutation name should be `createOrganization`
```
SRC_ENDPOINT="https://sourcegraph.test:3443" SRC_ACCESS_TOKEN=${SG_TEST_TOKEN} go run ./cmd/src orgs create -name ce-team
Organization "ce-team" created.
```

orgs: update `create` mutation

---

internal/batches/repozip/fetcher.go

When the download of a zip was aborted, it could've left behind a corrupted archive zip. This fixes it by first storing it to a temporary location and then creating the actual file atomically by doing os.Rename.
Closes https://github.com/sourcegraph/sourcegraph/issues/39743
Verified things still work as expected.

batches: Make sure no corrupted repozips are used

---

go.mod
go.sum

Tests should continue to pass. Manually tested with scip-ruby.

chore: Bump scip dependency for bug fixes.

---

go.mod
go.sum

Bumps sourcegraph/sourcegraph/lib, primarily for https://github.com/sourcegraph/sourcegraph/pull/39690
Existing unit tests

bump sourcegraph/sourcegraph/lib

---

CHANGELOG.md

Also bump to latest lib version.
go test and manual e2e run.

Prepare changelog for 3.43.0

---

README.markdown

docs: Link to usage docs, de-emphasize deprecated command.

---

cmd/src/extensions.go
cmd/src/extensions_list.go

Part of sourcegraph/sourcegraph#39044
Part of sourcegraph/sourcegraph#39043
While auditing the CLI functionality and requirements for the upcoming extensions deprecation, I noticed two areas that are currently not working well:
- The `sg extensions` command doesn't explain the upcoming deprecation yet. I've changed it to show the same text as sourcegraph.com cc @jjinnii @ryankscott @muratsu 
- The `sg extensions list` command did not forward the GraphQL error probably. This happens because the endpoint does not use the normal GraphQL error pattern for errors. [See this for more context](https://sourcegraph.com/github.com/ilscipio/sourcegraph/-/blob/cmd/frontend/registry/api/extension_connection_graphql.go?L192-204&utm_source=VSCode-2.2.7).
All other extension endpoints work as expected …

Prepare CLI for extension sunsetting

---

.goreleaser.yml
DEVELOPMENT.md

This PR will need to be reverted immediately before 4.0 is released, which will be accomplished by merging #828.
In terms of mechanics, we're relying on GoReleaser's [automatic detection of pre-releases](https://goreleaser.com/customization/release/#github), combined with [`.api/src-cli` automatically skipping pre-release versions of src-cli](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a00ffa24df05ad716def5d7a053ee5586c6b3194/-/blob/internal/src-cli/version.go?L116:31&subtree=true). The only actual changes we need to make are:
1. Choosing appropriate version numbers, which are now documented in `DEVELOPMENT.md`, and
2. Not pushing the `sourcegraph/src-cli` Docker image to the `latest` tag on `main` until we're ready to release 4.0.0 stable.
Closes …

Update release process until 4.0 stable is released.

---

.goreleaser.yml

Whatever version string sniffing goreleaser is doing isn't firing, so let's just force it. I'll add a revert to #828 for this as well.
We'll test this in the next 4.0.0 pre-release.

goreleaser: force releases to be marked as pre-release

---

cmd/src/doc.go

See [this Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1661140435839809). 
- Ran it locally to test that it generates new files

src doc: add code-intel and remove lsif

---

README.markdown

We received feedback that some users prefer using src-cli via docker. We publish an image for the purpose of serve-git, so was only documented there. This includes basic information for those inclined to use docker.
Test Plan: run the supplied command in docs

readme: add instructions for docker

---

cmd/src/users.go
cmd/src/users_clean.go
go.mod
go.sum

This draft PR tracks work on registering a new `src users` subcommand `src users clean` which allows admins to remove users in bulk given some conditions like admin status and days since last active use registered.
https://github.com/sourcegraph/sourcegraph/issues/40102
The command is still in development at the time of publishing this draft, it seems near MVP though
Two Additional nice to have features would be:
- output json file containing users removed and some data on the users (for use to send emails to removed users mostly)
- open an editor to compose general email to be sent to removed users and send. Functionality behind `-send-email` flag
_Please check carefully, I'm new at this!_
Manually test each command option against `cse-aws` and `cse-k8s`
Open to additional testing

Add `src users clean` to src-cli

---

cmd/src/batch_common.go

Fixes sourcegraph/sourcegraph#36304.
Ran `src batch preview -h` and enjoyed the new help text. Everybody loves their own brand.

doc: tinker with the help for -clean-archives for clarity

---

CHANGELOG.md

And 3.43.1 since we seemingly have missed that.
Docs change.

Add changelog entry for 3.43.2

---

cmd/src/batch_remote.go
go.mod
go.sum
internal/api/mock/api.go
internal/batches/service/remote.go
internal/batches/service/remote_test.go

Closes #841 
Changes to the GraphQL API broke the `batch remote` command. Updated `upsertEmptyBatchChange` to return the batch change ID and updated `createBatchSpecFromRaw` to accept the batch change ID.
Added Go Tests and did functional testing.

batches: Fix remote command - Batch Change ID not provided

---

.goreleaser.yml
DEVELOPMENT.md

This PR reverts #827, and must be merged before 4.0.0 stable is released.
At the same time this is merged, we should ensure the changelog reflects any releases made on `3.43`.
If #827 works, this will also work.

Revert 4.0-pre changes

---

cmd/src/code_intel_upload_flags.go

Manually tested by running with bad `-file` argument.

code-intel: Don't panic on errors in SCIP code paths.

---

cmd/src/extsvc.go
cmd/src/extsvc_add.go
cmd/src/extsvc_create.go

In the context of scaletesting, it's pretty useful to be able to add code hosts on the fly, while toying with a test instance. This PR adds such a command.
Manually tested.

Add a add subcommand to extsvc

---

cmd/src/code_intel_upload.go

Well, changing the message should not fail anything.

code-intel: Fix double word typo

---

cmd/src/batch_remote.go
internal/batches/service/remote.go
internal/batches/ui/tui.go

Closes sourcegraph/sourcegraph#42408.
Tested manually with large batch changes.

batches: show warning when batch changes are too large

---

CHANGELOG.md

We didn't have any feature changes/fixes for 4.1, but the Homebrew install availability is kinda a change so I decided to put that! We had a similar entry for when src-cli became available on npm.
Just docs change.

Prepare changelog for 4.1

---

internal/batches/workspace/executor_workspace.go

I added this as a stopgap to prevent accidental token leakage to cause upstream pushes to be allowed. This has been fixed on the executor side by using a new clone mechanism for repos, so this is no longer required.
Verified locally things still work as before.

ssbc: Don't drop repo origin

---

cmd/src/batch_exec.go

This is a requirement for secrets. The inline comment explains a bit why this is okay. This is all it takes from the src-cli side to implement secrets support :)
Tested E2E locally with the new secrets backend.

secrets: Allow using secrets from os.Environ

---

.github/workflows/goreleaser.yml

(Hopefully) closes https://github.com/sourcegraph/src-cli/issues/878.
We'll now use the GitHub-provided environment variable `GITHUB_REF_NAME` to determine the current (most recent) tag, rather than the unreliable sort. According to the [docs](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), this value will be:
> The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, `feature-branch-1`.
I was able to test this locally with [act](https://github.com/nektos/act) (thanks Bolaji!!) using simulated tag push events. I tested that a new tag triggered the "new latest" version of the workflow and that an older patch version tag triggered the patch …

Use `GITHUB_REF_NAME` to determine current tag for release workflow

---

internal/batches/docker/image.go

Recently a customer ran into _some_ issue but we weren't able to tell WHAT the issue was. This adds additional log output.
*Before*
```
✅ Parsing batch spec
✅ Resolving namespace
⠸  Preparing container images                                                                                                                                                 0%
❌ Error:
pulling image "ubunootu:18.04": pulling image: exit status 1
💡 The troubleshooting documentation can help to narrow down the cause of the errors:
https://docs.sourcegraph.com/batch_changes/references/troubleshooting
```
*After*
```
✅ Parsing batch spec
✅ Resolving namespace
⠏  Preparing container images …
```

Improve log output of docker pull errors

---

CHANGELOG.md
cmd/src/batch_common.go
internal/batches/ui/exec_ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/tui.go

Closes [#42885](https://github.com/sourcegraph/sourcegraph/issues/42885).
@BolajiOlajide caught this when working on [#31791](https://github.com/sourcegraph/sourcegraph/issues/31791). Luckily it was a quick implementation.
No tests. Did functional testing.
https://user-images.githubusercontent.com/38407415/195401837-ec1ab497-4207-4143-b94b-ade1eff1a4f5.mov

batches: Workspace file upload for local runs

---

CHANGELOG.md

Moved over one other item that got merged this morning.
Just a docs change.

Prepare changelog for 4.1.1

---

DEVELOPMENT.md

update release process

---

CHANGELOG.md
cmd/src/batch_common.go
cmd/src/batch_exec.go
internal/batches/executor/executor.go
internal/batches/executor/run_steps.go

This changes the default for `src batch exec` (used by SSBC) to run all step containers as root, and adds a flag to `src batch apply` and `src batch preview` to optionally do the same thing.
Fixes sourcegraph/sourcegraph#41836.
Tested with client and server side batch changes and a batch spec that outputs `id` into a file, with a container image that does not run as root by default (specifically, `haproxy:alpine`).

batches: improve handling of non-root steps

---

cmd/src/snapshot.go
cmd/src/snapshot_summary.go
cmd/src/snapshot_testcmd.go
internal/instancehealth/checks.go
internal/instancehealth/checks_test.go
internal/instancehealth/summary.go

These commands are tooling intended for use in on-prem-to-Cloud data migrations:
- `src snapshot summary` will generate a summary snapshot of an instance. APIs used here must be available in Sourcegraph 3.20 and later - see [RFC 760](https://docs.google.com/document/d/1IAgXmv2TbtU_rWXtph-KFc3qbqswREIAxO1rGALuoMQ/edit#bookmark=id.bc627wcztve6)
- `src snapshot test` will use the summary and other health indicators to try and show that the instance is healthy and in an expected state post-migration. APIs used here can be in the latest releases of Sourcegraph, because we will run a multi-version upgrade in Cloud to the latest version.
- The instance health checking components of this can in the future be re-used in a different command
Closes https://github.com/sourcegraph/customer/issues/1612 …

snapshot: add 'snapshot summary', 'snapshot test'

---

cmd/src/snapshot_databases.go
internal/pgdump/pgdump.go

Add simple utility for generating commands that can then be run/modified to create database dumps.
Right now, it's mostly for reference - as we build experience with different setups we can see if this can be made more flexible in the right ways. I believe a templating command like this is important to have, however, since we want to make sure all databases are exported and the correct flags are used with `pg_dump`, and documentation + manual copy-paste is error-prone.
Closes https://github.com/sourcegraph/customer/issues/1611 for now.
Also tested the kubectl commands on k8s.sgdev.org

snapshot: add pg_dump command builder with 'snapshot databases'

---

cmd/src/snapshot_upload.go
internal/pgdump/extensions.go
internal/pgdump/extensions_test.go

When uploading a snapshot, trim extension statements unsupported by Google Cloud SQL. We do this on upload so that the customer's copy of the dump remains unmodified (in case something goes wrong, we still have the original to work with - trimming can be disabled with `trim-extensions=false`).
Closes https://github.com/sourcegraph/customer/issues/1613
```
go run ./cmd/src snapshot upload -credentials='../cloud-data-migrations/misc/credential.json' -bucket='sourcegraph-cloud-data-migration-7ec798d67ff4'
```
See uploaded data

snapshot: trim extension statements from pgdump when uploading

---

CHANGELOG.md
cmd/src/batch_common.go
go.mod
go.sum
internal/batches/ui/exec_ui.go
internal/batches/ui/json_lines.go
internal/batches/ui/tui.go
internal/batches/watchdog/watchdog.go
internal/batches/watchdog/watchdog_test.go

Part 2 [#44432](https://github.com/sourcegraph/sourcegraph/issues/44432)
Closes [#44432](https://github.com/sourcegraph/sourcegraph/issues/44432)
Manually tested that the banner shows up when there's an error from getting the current context for docker.

add watchdog goroutine for docker

---

CHANGELOG.md
cmd/src/users.go
cmd/src/users_clean.go
cmd/src/users_prune.go

This PR refactors use of the `usageStatistics` `lastActiveUsage` table which caused the command to timeout during execution on instances with a sufficiently large number of users. See #848 
Instead the `aggregated_user_statistics` [table](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md?subtree=true) is used via the `site` graphQL endpoint
```graphql
query getInactiveUsers {
site {
users {
nodes {
id
username
email
siteAdmin
lastActiveAt
}
}
}
}
```
This has two benefits 
1. The backend to query `lastActiveAt` from the `site` graphQL endpoint is much more efficient than `usageStatistics`, and eliminates timeout concerns on many users instances
2. `aggregated_user_statistics` persists the date `lastActiveAt` eliminating the concern of `null` …

Rename users clean or prune -- use aggregated user statistics

---

DEVELOPMENT.md

That step seems to have gone missing.
Docs.

Fixup development docs

---

cmd/src/main.go
cmd/src/main_test.go

Passing `SRC_ADDITIONAL_HEADERS_AUTHORIZATION=...` and `SRC_ACCESS_TOKEN` at the same time leads to the latter overriding the former silently, making it quite difficult to spot. 
This PR surfaces the conflict as an error explictly advising to never set `SRC_ACCESS_TOKEN` in conjunction with the additional header.
Unit test + local run: 
```
~/work/src-cli/cmd  jh/fix-authorization-header-conflict $ SRC_HEADER_AUTHORIZATION="sourcegraph" SRC_ENDPOINT=https://sourcegraph.test:3443 go run ./... api -query='query { currentUser { username } }'
{
"data": {
"currentUser": {
"username": "sourcegraph"
}
}
}
~/work/src-cli/cmd  jh/fix-authorization-header-conflict $ SRC_ACCESS_TOKEN="foobar" SRC_HEADER_AUTHORIZATION="sourcegraph" SRC_ENDPOINT=https://sourcegraph.test:3443 go run ./... api …
```

Return an error when additional headers conflicts

---

internal/batches/ui/tui.go

The limit for changesets Batch Changes can create on unlicensed instances was increased from 5 to 10. This was accidentally reverted but is now [restored](https://github.com/sourcegraph/sourcegraph/pull/45688). This updates the TUI alert when running src-cli to create batch changes on an unlicensed instance.
N/A, just a string change.

batches: update limit in unlicensed alert

---

CHANGELOG.md
cmd/src/validate.go

context: https://sourcegraph.slack.com/archives/C022SPMNR0W/p1672950729445719
Implementation Engineer will use script to verify if instance is configured correctly and can create basic code insights and batch changes
locally tested using the scale test instance to create an insight
created yaml file 
```
createInsight:
title: "Javascript to Typescript migration" 
dataSeries:
[ {
"query": "lang:javascript",
"label": "javascript",
"repositoryScope": [
"github.com/sourcegraph/sourcegraph"
],
"lineColor": "#6495ED",
"timeScopeUnit": "MONTH",
"timeScopeValue": 1
},
{
"query": "lang:typescript",
"label": "typescript",
"lineColor": "#DE3163",
"repositoryScope": [
"github.com/sourcegraph/sourcegraph"
],
"timeScopeUnit": "MONTH",
"timeScopeValue": 1
}
]
```
ran `go run ./cmd/src validate …

Validate: add ability to check if code insights works on an instance

---

CHANGELOG.md
go.mod
go.sum

From https://github.com/sourcegraph/sourcegraph/pull/46281, will bump go.mod when its merged
Tested as part of the above linked PR

codeintel: print every error encountered while retrying code-intel upload instead of only final one

---

internal/instancehealth/checks.go

Removes usage of the endpoint deprecated in https://github.com/sourcegraph/sourcegraph/pull/46299, related to https://github.com/sourcegraph/customer/issues/1525
CI

instancehealth: remove monitoring check

---

CHANGELOG.md
internal/batches/ui/interval_writer.go
internal/batches/ui/interval_writer_test.go

batches: skip empty log output

---

CHANGELOG.md

update changelog 

---

internal/validate/install/install.go

Insights were automatically deleted, add option to keep insight created during validation via `deleteWhenDone`:
```yaml
externalService:
kind: GITHUB
displayName: srcgraph-test
deleteWhenDone: true
maxRetries: 5
retryTimeoutSeconds: 5
config:
gitHub:
url: https://github.com
orgs: []
repos:
- sourcegraph-testing/zap
searchQuery:
- repo:^github.com/sourcegraph-testing/zap$ test
- repo:^github.com/sourcegraph-testing/zap$@v1.14.1 test
insight:
title: "Javascript to Typescript migration"
dataSeries:
[ {
"query": "lang:javascript",
"label": "javascript",
"repositoryScope": [
"github.com/sourcegraph/sourcegraph"
],
"lineColor": "#6495ED",
"timeScopeUnit": "MONTH",
"timeScopeValue": 1
},
{
"query": "lang:typescript",
"label": "typescript",
"lineColor": "#DE3163",
"repositoryScope": [ …
```

Validate: add `deleteWhenDone` option to insights

---

CHANGELOG.md

Update `CHANGELOG.md` with changes needed for 4.4.1 release in step with `DEVELOPMENT.md` instructions. 
Ran `go test ./...` with all tests passing.

Release: update `CHANGELOG.md` for release process of 4.4.1

---

cmd/src/code_intel_upload.go
cmd/src/code_intel_upload_flags.go

Diff is pretty self-explanatory. See https://github.com/sourcegraph/sourcegraph/pull/47532.
Going to create a local docker image and test the auto-indexing flow locally to make sure we don't continue to clobber the `/.executor` route prefix.

Do not override executor queue endpoints

---

cmd/src/cmd.go
cmd/src/snapshot_testcmd.go
internal/instancehealth/checks.go
internal/instancehealth/checks_test.go
internal/instancehealth/summary.go

Test plan:
`src snapshot test` runs successfully and fetches perms sync information from a local sg instance.
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/47933

permissions-center: use new `permissionSyncJobs` query.

---

internal/servegit/serve.go

WalkDir was introduced in go1.16 suits our use case while being more efficient.
Test Plan: go test

servegit: use more performant WalkDir

---

cmd/src/validate_kube.go
internal/validate/kube/aks.go
internal/validate/kube/kube.go

Manual testing of failing and passing cases.

validate persistent volumes for aks clusters

---

internal/validate/kube/kube.go

- Before, clusters/namespaces would pass all validations even if no Sourcegraph instance was installed.
- Now: pods, services, connections and PVC validations fail with a warning if none exist.
Manually tested on AKS, GKE clusters with and without a Sourcegraph instance.

Adds conditions for clusters that do not have Sourcegraph installed.

---

cmd/src/snapshot_databases.go
cmd/src/snapshot_restore.go
internal/pgdump/pgdump.go

Snapshot Restore generates commands to restore dumped snapshots to a Sourcegraph instance
Usage:
After generating a dump the restore commands can be generated with
```
src snapshot restore <docker|kubectlpg_dump>
```
The `--run` command can be used to attempt to automatically run these commands. Useful e.g. in the AMIs e.g.
```
src snapshot restore --run <docker|kubectlpg_dump>
```
- Changed snapshot args ordering
- To get the --run flag to work it was necessary to change arg ordering as Go's flag package requires all flags come before non flag args
```
src snapshot databases docker --run
src snapshot databases --run docker
```
- Removed the -t flags from <docker|kubectl> exec
- afaik only -i should be necessary for input/output redirection. Without -t we get better compatibility …

Add Snapshot Restore command

---

cmd/src/version.go

This could be confusing, it only says server error and prints details on that, so it sounds like src-cli just broke? At least it confused people at Sourcegraph. This prefixes it with some more context to help that.
Error shows correctly, tested manually.

version: Clarify origin of error

---

cmd/src/admin.go
cmd/src/admin_create.go
internal/lazyregexp/lazyregexp.go
internal/users/admin.go

Add `src admin create` command to setup an initial admin account on a new deployment of Sourcegraph. This is mainly useful for CI pipelines and integration testing purposes in which a Sourcegraph deployment will be deployed in an automated way.
This functionality was previously tied to the experimental `src validate` command but was removed.
Locally tested changes using latest Sourcegraph Helm install.
ran go test ./... - all tests passing
ran staticcheck ./... - no issues found in new code

Admin: add `src admin create` command

---

cmd/src/validate_install.go
internal/validate/install/config.go
internal/validate/install/github.go
internal/validate/install/insight.go
internal/validate/install/install.go

Previously `src validate install` required the env var `SRC_GITHUB_TOKEN` to be set, even if no external services were being added. This also blocked validating queries with repositories that already existed on a Sourcegraph deployment.
This fix allows `src validate install` to be run without requiring the `SRC_GITHUB_TOKEN` env var to be set, as well as validating queries with repositories that already exist on a deployment.
Fixes #956 
Fixes https://github.com/sourcegraph/sourcegraph/issues/47576
Locally tested changes using latest Sourcegraph Helm install.
ran go test ./... - all tests passing
ran staticcheck ./... - no issues found in new code

Validate: no longer require SRC_GITHUB_TOKEN to be set

---

.github/workflows/goreleaser.yml

To make the pre-release step `Copy previous release` idempotent in case of failures, we will allow empty commits to the homebrew tap repo. That way, even if the step already ran and succeeded, it can successfully be re-run with no change.
About to test with an actual release.

Allow empty commits in copy pre-release step

---

internal/validate/install/install.go

Add fix to `src validate install` command.
- Ran `go test ./...` with all tests passing.
- Ran `staticcheck ./...` with no new warnings returned.
- Validated changes work with Sourcegraph 5.0.0 (see below)

Validate: add fix for `src validate install` failure with Sourcegraph v5.0.0

---

.tool-versions
Dockerfile

Update to 1.19.8 because it fixes multiple vulnerabilities.
[_Created by Sourcegraph batch change `evict/update-to-go1.19.8`._](https://sourcegraph.sourcegraph.com/users/evict/batch-changes/update-to-go1.19.8)
Verify build locally.

Update to Go 1.19.8

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml

The Go Lint and Go Test workflows named their jobs `go-test`, which prohibited the Go Test workflow from running - specifically the ubuntu one, as the `go-test` job on ubuntu-latest also exists in the Go Lint workflow. Updated the name and now the Go Test Ubuntu latest action is running again.
Go Test actions are running

actions: fix job name conflict

---

.vscode/settings.json
CHANGELOG.md
cmd/src/repos.go
cmd/src/repos_add_metadata.go
cmd/src/repos_delete_metadata.go
cmd/src/repos_update_metadata.go

Part of https://github.com/sourcegraph/pr-faqs/issues/96.
This PR adds `src repos {add|update|delete}-metadata -repo-name` flag support
**NOTE**: When using `repo-name` flag, it makes an extra GQL query to get a repo ID. This is made for back compat purposes instead of introducing breaking change and updating underlying add/update/delete repo metadata GQL query.
- Add/update/delete using `repo` flag as previously
- `go run ./cmd/src repos add-metadata -repo=$repoID -key=test`
- `go run ./cmd/src repos update-metadata -repo=$repoID -key=test -value=value`
- `go run ./cmd/src repos delete-metadata -repo=$repoID -key=test`
- Add/update/delete using `repo-name` flag as previously
- `go run ./cmd/src repos add-metadata -repo-name=$repoName -key=test`
- `go run ./cmd/src repos update-metadata …

(feat) add "src repos {add|update|delete}-metadata -repo-name" flag support

---

cmd/src/scout_usage.go
internal/scout/usage/docker.go

Test manually:
- with other sub commands in different orders
- on healthy and unhealthy docker deployments of sourcegraph

scout/usage: add `--container` flag to `src scout usage`

---

internal/scout/advise/advise.go
internal/scout/advise/advise_test.go
internal/scout/advise/k8s.go
internal/scout/kube/kube_test.go

Adds more tests for the `kube` package and creates test file for `advise` package
This commit is only tests.

test advise package and more tests for kube package

---

.github/workflows/goreleaser.yml

This command is deprecated and I suspect is causing an error in the release.
N/A

use --clean instead of --rm-dist

---

cmd/src/main.go

There is no `src upload` command. So let's remove it from the help text.
Test Plan:
```
φ go run ./cmd/src upload
src: unknown subcommand "upload"
Run 'src help' for usage.
exit status 1
```

help text: remove 'upload' command that does not exist

---

CHANGELOG.md
cmd/src/code_intel_upload.go
cmd/src/code_intel_upload_flags.go

Previously, we were doing SCIP detection before parsing cli flags. As SCIP detection makes a HTTP request, this meant it wasnt configured with the (global :grimacing:) API client flags
Ran manually to confirm flag is picked up at the correct time with :sparkles: print statements :sparkles:

codeintel: handle -insecure-skip-verify in SCIP endpoint detection

---

cmd/src/batch_common.go
internal/batches/service/remote.go

Two recent issues were found.
* When a file exceeded the size limit, the file name was not in the error. This made it hard to tell which file is causing the issue
* The error being returned was still set after logging as a warn. This made it so the program still errored out
[Thread](https://sourcegraph.slack.com/archives/C04M9JE73E1/p1691434360532449) of context.
Existing tests cover changes.

batches: File upload error handling

---

internal/batches/docker/info.go
internal/batches/docker/info_test.go

- use host CPU from Host property if available
This partially fix https://github.com/sourcegraph/src-cli/issues/855
I have run unit tests.
Also tried it locally with my podman. 
Still getting some error regarding volumes and tmp files. But that seems more related to podman itself probably.
_I need someone to test it also with docker. If it's still work._
- tested, it should work

docker/info use format JSON

---

internal/batches/workspace/volume_workspace.go
internal/batches/workspace/volume_workspace_test.go

If workspace preparation fails, the temporary Docker volume is not cleaned up.
I'll need help filling in this bit. Apart from manually inducing an error with the workspace process, how else? I could possibly build locally a broken batch-change container image that doesn't have Git nor unzip?

Clean up volumes if workspace preparation fails

---

CHANGELOG.md

Changelog entry for https://github.com/sourcegraph/src-cli/pull/1023
N/A changelog entry

changelog entry for codeintel upload concurrency flag

---

cmd/src/code_intel_upload.go

Based on discussion in Slack where a customer wasn't certain about
how to use `src code-intel upload` with Perforce.
n/a

docs: Tweak examples for src code-intel upload

---

cmd/src/code_intel_upload_flags.go

Don't convert SCIP to LSIF, don't attempt to upload the index
Fixes https://github.com/sourcegraph/src-cli/issues/1032
Manually tested with a bogus token

codeintel: Fail fast on 401 failure in SCIP detection

---

deps.bzl
go.mod
go.sum
internal/servegit/serve.go

Before this if the git command failed we would nil panic since the Logger on gitservice.Handler was not set. This commit updates us to the latest version of lib which instead takes in an error hook so we can use the attached stdlib logger.
Corresponding PR at https://github.com/sourcegraph/sourcegraph/pull/56611
Test Plan: go test

servegit: use error hook

---

.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml

YAML sees '1.20' as a number and so it cuts off the trailing 0, leading to the action setting up go 1.2. So we add a '.x' to make it a string.
[Action seems to be checking out 1.20 ](https://github.com/sourcegraph/src-cli/actions/runs/6803034582)
CI

goreleaser: quote go version number

---

internal/batches/executor/run_steps.go
internal/batches/util/repo.go

During batch execution, we were creating the template variable with no branch name set, which meant that steps would just get an empty string for the branch name if it is used in a step.
Fixes https://github.com/sourcegraph/sourcegraph/issues/59250
Ran a batch change that uses the `${{ repository.branch }}` template variable and ensured that the variable gets populated with a non-empty string.

Batches: populate branch name during template resolution

---

npm-distribution/package.json

Next release should include a README in `npmjs.com`

npm: add readme when prepacking

---

.goreleaser.yml

After bumping the goreleaser version, a CI step is failing because we are using a field that was deprecated. [Example](https://github.com/sourcegraph/src-cli/actions/runs/8542214451/job/23403373409?pr=1065). This just follows the deprecation instructions to fix it. 
Goreleaser step passes.

Chore: fix deprecated field

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.github/workflows/pr-auditor.yml
go.mod
go.sum

Needed for using updated libraries from monorepo
Covered by existing tests

chore: Bump to Go 1.22.2

---

.golangci.yml
dev/golangci-lint.sh
internal/batches/ui/task_exec_tui_test.go
internal/validate/kube/kube.go

When src-validate fails to connect to a service, name that service in the error message.
There are no current automated tests for this error message, and this commit does not add any, admittedly. This is _arguably_ only a behavioral change if an external tool is parsing this particular error message.

validate: add context to connection error

---

CHANGELOG.md
internal/validate/kube/kube.go

Remove "connections" validation. This checked that various services were TCP-reachable (and resolvable by kube-dns), from various pods. For example, it checked that pgsql was reachable from frontend. This particular validation wouldn't always be useful, e.g. when external postgres clusters were used. It was also failing due to the removal of `nc` from base images.
This upstream health-checking _could_ be replaced by doing this check in the readiness probe handler. For example: frontend pods could check the availability of a pgsql connection, and fail their readiness probe if that is unavailable. This is a contentious topic however and should be approached with caution: mean-time-to-recovery can actually substantially increase under some configurations due to cascading failing readiness …

validate subcommand: various changes

---

CHANGELOG.md
cmd/src/servegit.go
internal/servegit/serve.go

Fixes urls to doc pages that do not resolve anymore
- Test new urls are valid

fix(Source): Fix broken code host doc links

---

npm-distribution/.gitignore
npm-distribution/copy-files.js
npm-distribution/install.js
npm-distribution/package.json

Fixes #1050. Previously, it was not possible to install src-cli via npm on Windows. It was also not possible to publish the npm package from a Windows computer. This PR fixes both problems. The second problem had to be solved so I could manually test the fix for this PR.:
Manually tested locally on a Windows computer
- Ran `verdaccio`
- Set package version to 5.4.0
- `pnpm unpublish --force`
- `pnpm publish`
- Created new project, ran `pnpm init`
- `pnpm add @sourcegraph/src`
- `pnpm exec src login`, confirmed it worked

Fix windows installation

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.github/workflows/pr-auditor.yml
.tool-versions
Dockerfile
go.mod

Needed for fixing CVE in executor-* (executor, executor-kubernetes, bundled-executor) docker images
https://github.com/advisories/GHSA-49gw-vxvf-fc2g, https://github.com/advisories/GHSA-2jwv-jmq4-4j3r
ref: https://github.com/sourcegraph/sourcegraph/issues/63796
- CI

chore(security) : upgrade golang to 1.22.5 to fix CVE

---

cmd/src/cmd.go

Addresses https://github.com/sourcegraph/src-cli/issues/689
Tested manually. Re-directed `src` command and sub-commands outputs for default usage (no args) and with `help`/`--help` args and checked all output was captured.

Consistently redirect usage examples to stdout

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.tool-versions
CHANGELOG.md
Dockerfile
go.mod

Update to latest 1.22 version of Go
Can we cut a new release of src-cli for the release today as this fixes a CVE.
- CI
- Build src-cli locally and run govulncheck
- Build docker image locally - **this fails, but also fails on `main`. Is this expected to work?** See comment below for output.

chore(security): Update go version to 1.22.8

---

.gitignore
cmd/src/main.go
cmd/src/sbom.go
cmd/src/sbom_fetch.go
cmd/src/sbom_utils.go

Add new `src sbom` command to allow customers to fetch and verify [SBOMs](https://github.com/sourcegraph/sourcegraph/pull/566/commits).
This command will fetch SBOMs from our container registry, and validate them against a published public key.
To test this out locally:
```
$ go run ./cmd/src sbom fetch -v 5.8.287 --internal --insecure-ignore-tlog
Fetching SBOMs and validating signatures for all 55 images in the Sourcegraph 5.8.287 release...
⚠️ WARNING: Transparency log verification is disabled, increasing the risk that SBOMs may have been tampered with.
This setting should only be used for testing or under explicit instruction from Sourcegraph.
✅ us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/appliance
✅ us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/batcheshelper …
```

Add SBOM command

---

CHANGELOG.md
cmd/src/sbom_fetch.go

Add missing changelog entry for https://github.com/sourcegraph/src-cli/pull/1115.
Also improve the error message when an unsupported version is passed:
Unsupported version <=5.8.0:
```
> go run ./cmd/src sbom fetch -v 5.8.0 --internal --insecure-ignore-tlog
unsupported version 5.8.0: SBOMs are only available for Sourcegraph releases after 5.8.0
```
Supported version >5.8.0:
```
>  go run ./cmd/src sbom fetch -v 5.8.287 --internal --insecure-ignore-tlog
Fetching SBOMs and validating signatures for all 55 images in the Sourcegraph 5.8.287 release...
⚠️ WARNING: Transparency log verification is disabled, increasing the risk that SBOMs may have been tampered with.
️          This setting should only be used for testing or under explicit instruction from Sourcegraph.
✅ …
```

sboms: Update changelog and improve error message

---

CHANGELOG.md
cmd/src/cmd.go

#1105 introduced a bug spotted in https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1728932051783959 where commands that can take no arguments wouldn't run:
```
❯ src login
'src login' helps you authenticate 'src' to access a Sourcegraph instance with your user credentials.
Usage:
src login SOURCEGRAPH_URL
```
This was caused by `if len(args) == 0` which captured commands that didn't take arguments like `login`.
Reading through the original PR and discussion, I agree with [this logic](https://github.com/sourcegraph/src-cli/issues/689#issuecomment-1050014015) for choosing when to output to stdout/err.
There was another minor bug in the old code that I've fixed - `cmd.flagSet.Parse()` will print help to **stderr** and exit if passed a command that doesn't take subcommands and the `--help` …

Fix #1105: Execute commands with zero arguments correctly

---

CHANGELOG.md
cmd/src/login.go
cmd/src/login_test.go
cmd/src/main.go
cmd/src/main_test.go
dev/test-proxies.sh
internal/api/BUILD.bazel
internal/api/api.go
internal/api/proxy.go
internal/api/test_unix_socket_server.go

This PR adds support for explicit HTTP(S), SOCKS5 and UNIX Domain Socket proxies that can be set using the `SRC_PROXY` environment variable:
```
SRC_ENDPOINT=https://sourcegraph.sourcegraph.com \
SRC_ACCESS_TOKEN=deadbeef \
SRC_PROXY=https://localhost:8080 \
src login --insecure-skip-verify=true
✔️  Authenticated as peter.guy on https://sourcegraph.sourcegraph.com
```
CI tests all pass.
Added more config tests.
*Option 1:*
Use `dev/test-proxies.sh`. 
Follow the instructions in comments at the beginning, then run the script.
*Option 2:*
0. Install `socat` and `mitmproxy`
```
brew install socat mitmproxy
```
3. In two separate terminals, run:
```
socat -d -d unix-listen:${HOME}/src-proxy.sock,fork tcp:localhost:8080
```
and
```
mitmproxy -v
```
4. Check out this branch and build `src-cli`: …

Add proxy support

---

CHANGELOG.md
cmd/src/sbom_fetch.go
cmd/src/sbom_utils.go

- Update SBOM output file format to `.cdx.json`
- Remove an additional layout of JSON wrapping, as this isn't handled by some SBOM parsers
- Tested locally
```
> go run ./cmd/src sbom fetch -v 5.9.45
Fetching SBOMs and validating signatures for all 39 images in the Sourcegraph 5.9.45 release...
✅ sourcegraph/appliance
✅ sourcegraph/batcheshelper
✅ sourcegraph/bundled-executor
✅ sourcegraph/cody-gateway
[...]
> grype sourcegraph-sboms/sourcegraph-5.9.45/sourcegraph_gitserver.cdx.json
✔ Vulnerability DB                [no update available]  
✔ Scanned for vulnerabilities     [8 vulnerability matches]  
├── by severity: 0 critical, 1 high, 2 medium, 1 low, 0 negligible (4 unknown)
└── by status:   8 fixed, 0 not-fixed, 0 ignored 
NAME                          INSTALLED  FIXED-IN   TYPE …
```

Update SBOM file format and extract different payload

---

cmd/src/colors.go
cmd/src/gateway.go
cmd/src/gateway_benchmark.go
cmd/src/main.go

Adds the `src gateway benchmark` command to the tool.
https://github.com/sourcegraph/sourcegraph/pull/1526 adds some new endpoints that this benchmarking script uses.
The benchmarking tool compares ~three~ two routes using the endpoints added in above PR:
1. Sourcegraph HTTP → Cody Gateway HTTP
2. Sourcegraph HTTP → Cody Gateway WebSocket
3. (There should be a third one: Sourcegraph WebSocket → Cody Gateway WebSocket, but I haven't been able to make that endpoint work so it's currently not added to this script.)
(Description WIP)
- `brew install ngrok/ngrok/ngrok` if you don't have ngrok
- Run `ngrok http http://localhost:9992`
- Copy the `*.ngrok-free.app` URL from the "Forwarding" section of ngrok's output to your `dev-private/enterprise/dev/site-config.json` as the "modelConfiguration" …

feat/gateway: Add `src gateway benchmark` command

---

cmd/src/login.go
cmd/src/login_test.go
go.mod
go.sum

This PR fixes two issues- 
1. #716
Improved the error message in `login.go` to emphasize that the access token is created by going to the webpage and the env vars are updated in the terminal. 
3. #1114
As https://github.com/sourcegraph/sourcegraph was changed to https://github.com/sourcegraph/sourcegraph-public-snapshot
The dependency `github.com/sourcegraph/sourcegraph/lib` was not found. To fix this, a replace directive was added in the go.mod to update the path of that dependency to the new one. 
1. Tested by running `go run ./cmd/src login` to get the following as the expected result- 
```
❌ Problem: No access token is configured.
🛠  To fix: Create an access token by going to https://sourcegraph.com/user/settings/tokens, then set the following environment variables in your terminal: …
```

Access token err msg

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.github/workflows/pr-auditor.yml
.tool-versions

Update golang version referenced in tools-version to be 1.23.2, as that is the version required by the sourcegraph-public-snapshot/lib go.mod
Tested locally

update golang tools version

---

cmd/src/gateway_benchmark.go
go.mod
go.sum

Continues development of #1124
* Updates Go version used in this repository (I had to do this to develop, see https://sourcegraph.slack.com/archives/C07KZF47K/p1731627487087909)
* Checks the status code returned by HTTP endpoints.
* Updates Sourcegraph HTTP endpoints to `/.api/gateway` and `/.api/gateway/websocket`.
* Updates gateway HTTP endpoints to `/v2` and `/v2/websocket`
* Adds websocket client.
* Respects `-gateway` parameter and `SRC_ENDPOINT`/`SRC_ACCESS_TOKEN`
This should be sufficient for testing against the actual production endpoints once they are added / working / live in prod.
Not tested yet since endpoints are not live yet. Command not in use yet, so no risk.

update Go version; add websocket / correct endpoints to 'src gateway benchmark'

---

cmd/src/gateway_benchmark.go

Fix body closing func format to match the expectations in our CI.
CI

Fix body closing format for CI

---

cmd/src/gateway_benchmark.go

Minor changes which pair with https://github.com/sourcegraph/sourcegraph/pull/2119and help debug e.g. WebSocket connection issues
Manually tested via running:
```
go install ./cmd/src && ~/.gobin/src gateway benchmark --gateway http://localhost:9992 --sourcegraph http://localhost:3082 --requests 10000
```
With this site config in a dev instance:
```
"modelConfiguration": {
"sourcegraph": {
"endpoint": "http://localhost:9992"
// "endpoint": "https://cody-gateway.sgdev.org"
}
},
```
Running this PR: https://github.com/sourcegraph/sourcegraph/pull/2119
Which produces these results:
```
Endpoint                  | Average    | Median     | P5         | P75        | P80        | P95        | Total      | Success   
-------------------------------------------------------------------------------- …
```

gateway: benchmark: use POST, improve logging slightly

---

cmd/src/gateway_benchmark.go

This fixes a silly mistake I made that caused HTTP tests never to be called.
Tested locally

gateway benchmark: Fix httpEndpointConfig pointer type issue

---

cmd/src/gateway_benchmark.go

The first commit here replaces the authentication with a simpler / more correct implementation (no transport) and improves usage doc commands slightly.
The second commit fixes a major issue: we would connect the websocket at the very start, which meant that if the tests which run _before_ we use the websocket take >60s.. by the time we use the websocket, the server would already consider the connection dead due to inactivity. This fixes the issue by only connecting the first time we want to use the connection, and also adding reconnect logic.
Manually tested

gateway: benchmark: fix 'all websocket requests fail' case

---

cmd/src/gateway_benchmark.go

In my last change, I forgot to set auth headers for the websocket connection. This fixes that so both dotcom and sg04 work properly.
manually tested against SG04

gateway: benchmark: fix websocket auth

---

cmd/src/gateway_benchmark.go

Minor formatting issue which caused the table to not be aligned.
Test Plan: Ran the shared incantation with "--requests 1" and the table looked good.

gateway: benchmark has same alignment for header and rows

---

cmd/src/batch_common.go
cmd/src/batch_new.go
cmd/src/batch_remote.go
cmd/src/batch_repositories.go
cmd/src/batch_validate.go
internal/batches/features.go
internal/batches/service/service.go

Tested with `-get-curl` and verified the fix, for Linear issue SRCH-1337.

fix: batches now respects skip-errors for version check

---

CHANGELOG.md
go.mod
go.sum

Update x/crypto to latest version to patch CVE-2024-45338.
This CVE likely doesn't affect us, but updating to avoid it appearing in scans.
- Local scan of go.mod to check fix
- CI

chore/security: Update x/net to latest version 

---

cmd/src/gateway_benchmark.go
cmd/src/gateway_benchmark_stream.go

Helps with https://linear.app/sourcegraph/issue/PRIME-651/look-into-cloudflare-settings-for-gateway-vs-dotcom-streaming.
- Uses the benchmarking endpoints that were introduced in https://github.com/sourcegraph/src-cli/pull/1124 and its cousin PRs to sg/sg
- Adds a flag that sets the special header `cody-core-gc-test` that Security enabled for us which disables WAF (Web Application Firewall) headers for the request that contains it.
The goal is to run this on a few dev machines to learn more about how Cloudflare might affect latency.
Created this PR to store and share the code we used for this particular benchmarking.
I don't intend to merge this.

Add --use-special-header to gateway benchmark (PRIME-651)

---

cmd/src/gateway.go
cmd/src/gateway_benchmark.go
cmd/src/gateway_benchmark_stream.go

This PR adds a new benchmarking script similar to `gateway benchmark` with the capability to test the actual code completion endpoints of SG and CG.
This is mainly for https://linear.app/sourcegraph/issue/PRIME-655/investigate-why-double-streaming-incours-an-additional-123ms-of.
Why draft: Right now, I don't intend to merge this. The script should be somewhat reconciled with `gateway benchmark` to make it merge-ready.
I used the tool after the change.

Add "gateway benchmark-stream"(PRIME-655)

---

CHANGELOG.md
cmd/src/sbom.go
cmd/src/sbom_fetch.go
cmd/src/sbom_utils.go
cmd/src/signature.go
cmd/src/signature_fetch.go

Implement verification of container signatures for release images. This allows customers to easily verify the signatures we started publishing in [SEC-2445](https://linear.app/sourcegraph/issue/SEC-2445/sign-public-releases).
The implementation shares several helper functions with the `src sbom fetch` command, as both fetch information about releases, talk to our container registries, and use `cosign` behind the scenes.
The verification process is:
- Fetch list of images in $release from GCS bucket
- Fetch our public key from GCS bucket
- Verify signature of each image at the release tag using `cosign verify` with our public key
- Output image digests once they're verified
Digests can then be used or checked against our deployment configs by customers. Customers could also use the …

feature/security: Implement image signature verification

---

cmd/src/format.go
cmd/src/search_jobs.go
cmd/src/search_jobs_cancel.go
cmd/src/search_jobs_create.go
cmd/src/search_jobs_delete.go
cmd/src/search_jobs_get.go
cmd/src/search_jobs_list.go
cmd/src/search_jobs_logs.go
cmd/src/search_jobs_results.go

What started as a simple linter placating ended up with adding support for numeric search job ids instead of needing to use the base64-encoded values.
Not sure how helpful that is.
TBD

Bike-shedding on search jobs

---

cmd/src/login_test.go

Fixes test that was broken by #1152

fix: remove trailing period in error message test

---

.github/workflows/goreleaser.yml

Update GH action token reference. Previous token did not have proper scope needed for GH action
CI

fix(rel): udpate token reference

---

.github/workflows/goreleaser.yml

Update GH token references for other GH actions
CI

fix(rel): udpate token references for other GH actions

---

DEVELOPMENT.md

This adds a note about running `sg bzael configure` this is sometimes necessary when some of the digests are changed during the release
Tested in release

fix(release): Add note in release procedure doc

---

CHANGELOG.md
cmd/src/sbom_fetch.go
cmd/src/sbom_utils.go

When running `src sbom fetch`, all container images of the given release version would always get their SBOMs fetched; this leads to HTTP 429 rate limit blocks from Dockerhub if more than 2 versions are fetched. Allowing filtering of image names means that more versions can have SBOMs fetched for fewer images.
Amp wrote the code and tested it itself
I was also able to run it successfully in my Bash script:
```bash
declare -a versions=("6.4.1203" "6.4.0" "6.3.4167" ... "5.8.0")
for version in "${versions[@]}"
do
go run ./cmd/src sbom fetch -v "$version" --image 'postgres*' --exclude-image '*exporter*,*codeinsights*'
done
```
- Amp thread [here](https://ampcode.com/threads/T-4c37a0d3-470e-46aa-9e0b-100601e0e9ac)
- Slack thread [here](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p17489880 …

Add image name filters to src sbom fetch command

---

.github/workflows/go-ci.yml

This is required so that we can make the CI checks mandatory in branch protection - otherwise the names of the jobs will keep changing when we update Go.
The next step will be to make the new job mandatory in branch protection.
[SEC-3159: Investigate missing required checks on src-cli](https://linear.app/sourcegraph/issue/SEC-3159/investigate-missing-required-checks-on-src-cli)
Manual testing, which I'll have to do after merging.

Add a check that only succeeds if all matrix tests pass

---

renovate.json

This PR adds values to the `renovate` bot's config to let it automerge PRs when CI passes. It will automatically wait for CI checks to pass; this config only bypasses the need for human review.
CI Passes

chore(cli): automerge setting for renovate bot

---

Dockerfile
Dockerfile.release
docker/batch-change-volume-workspace/Dockerfile

Update the version of alpine in our release image to 3.22.
Built and run locally + CI

Update alpine version for release image
