sourcegraph/src-cli

README.md

Figured if all other OS have this Windows should have it too. Tested and works.

Add Windows command line installation instructions

---

cmd/src/lsif.go
cmd/src/lsif_upload.go
cmd/src/main.go

This adds a command `src lsif upload` that compresses an LSIF dump through the frontend API.

Add lsif upload command.

---

cmd/src/lsif_upload.go

This is for multi-project support https://github.com/sourcegraph/sourcegraph/pull/5985

Add lsif -root flag

---

cmd/src/lsif_upload.go

See https://github.com/sourcegraph/sourcegraph/pull/6077

LSIF: add flag to skip validation

---

cmd/src/lsif_upload.go

See https://github.com/sourcegraph/sourcegraph/pull/6113

LSIF: replace LSIF upload token with GitHub token

---

cmd/src/lsif_upload.go

See https://github.com/sourcegraph/sourcegraph/pull/6413.

Remove LSIF upload skip validation option.

---

cmd/src/lsif_upload.go

This applies defaults to `-repo`, `-commit`, `-file`, and `-root`. See https://sourcegraph.slack.com/archives/CHXHX7XAS/p1572901719287700

LSIF: apply defaults

---

README.md

From feedback https://github.com/sourcegraph/lsif-cpp/issues/4

Add build-from-source instructions

---

cmd/src/extensions.go

Continuation of https://github.com/sourcegraph/src-cli/pull/82

Add docs for extension copy

---

cmd/src/actions_exec_backend_runner.go

Before this we just reported that the process was killed, but not that the kill signal was triggered by the timeout.

Properly report when command reached timeout

---

cmd/src/actions_exec.go

Only add count:999999 to scopeQuery if no count is given

---

cmd/src/actions_exec.go

Before this change it was possible to define a "docker" step that simply did
nothing by using unused keys in the steps definition.
For example, if you specified this step:
{"type":"docker", "dockerimage":"foobar"}
You wouldn't get an error that "dockerimage" is wrong. Now you do.

Validate that either Dockerfile or Image are specified

---

cmd/src/format.go

Add link for update workflow

---

cmd/src/format.go

Quoting my comment here: I know that it's hacky to do this in the
formatting helper, but for now I think this is the easiest change to
make without introducing a whole lot of global state and/or mixing the
update property into the CampaignPlan.
If someone knows of a better way, let me know.

Only show "update campaign" message if it's supported

---

cmd/src/campaigns_create.go
cmd/src/campaigns_create_test.go
cmd/src/format.go

Thanks @efritz for the shoutout in https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/245

Append -0 to versions in version check to allow RC versions

---

cmd/src/actions_exec_backend_runner.go

This fixes #109 by using Go's archive/zip package to unzip files.
(The code is taken from here and slightly modified: https://golangcode.com/unzip-files-in-go/)
It fixes the "interactive" problem, because it silently ignores
case-sensitive naming conflicts, which is what you get when using macOS'
Finder's unzip utility and unzip on the CLI. "Silently ignores" sounds
bad but I think it's what you expect to happen on macOS.
It also handles the chinese characters correctly.
@eseliger Can you test this with your repositories in #109?

Use Go's archive/zip to unzip repository archives

---

cmd/src/actions_exec.go
cmd/src/actions_exec_backend_runner.go
cmd/src/actions_exec_logger.go

Remove support for inline dockerfiles

---

cmd/src/lsif_upload.go

- Fix ambiguous documentation for the repo (should it be a cloneable URI?, etc).
- Fix incorrect default for root.

Update LSIF upload parameter docs

---

cmd/src/actions_exec_backend_runner.go
cmd/src/actions_exec_logger.go
go.mod
go.sum

Log prefixed stdout/stderr of steps to stderr if verbose mode is on

---

cmd/src/actions_exec.go

This fixes https://github.com/sourcegraph/src-cli/issues/117 by
cancelling the global context when Ctrl-C is hit.
The cancelation propagates down to `runAction` where containers that are
still running are killed.

Cancel context on os.Interrupt

---

cmd/src/actions_create.go
schema/actions.schema.json

This fixes #153 but depends on #171.

Add 'src action create' cmd to create empty action definition

---

README.md

It seems like my previous changes in #182 didn't work, so I switched to these, which do seem to work.

Reduce size of image in README

---

.gitignore
cmd/src/actions_exec.go

Closes: https://github.com/sourcegraph/src-cli/issues/189

Warn user when scopeQuery doesn't match anything

---

cmd/src/actions_exec.go
cmd/src/actions_scope_query.go

Closes #186 
I also retried the action that I reported https://github.com/sourcegraph/src-cli/issues/185 on, it is also fixed by this change: Closes #185

Only yield repositories from supported codehosts

---

cmd/src/actions_exec.go
cmd/src/actions_exec_logger.go

Pull missing docker images automatically

---

cmd/src/extensions_publish.go
internal/campaigns/logger.go

I just ran [staticcheck.io](https://staticcheck.io) over the repository
and these came up.

Fix warnings produced by staticcheck

---

cmd/src/campaigns_preview.go

campaigns: fix usage wording

---

internal/campaigns/executor.go

I ran into this yesterday with Chris: we ran a command across multiple
repositories and in one repository it didn't produce a diff.
That's totally to be expected, since you don't know which command will
produce which diff in which repository.
The problem is that src-cli then sends up the changeset spec, even
though the diff is empty and we then try to apply the diff in gitserver,
which is where it fails (bonus: our error message looked really good!)
This commit here fixes it by not adding a spec with an empty diff to the
"list of completed specs".
I've looked at a few places where we could add this check (for example:
right before we make the GraphQL request we could do an early exit, or
before we add it to the cache, ...) and I'm still not 100% whether
that's the best place.
But I think …

Do not create ChangesetSpecs on server with empty diff

---

DEVELOPMENT.md

It took me a minute to find the right place to monitor.

development: include direct Travis branch link

---

.github/workflows/go-ci.yml
.github/workflows/goreleaser.yml

No idea if this works, let's try :>

Run on all branches AND all tags

---

.github/workflows/goreleaser.yml

Our tags don't start with a 'v', mind tricked me :)

Fix goreleaser tag detection

---

cmd/src/lsif_upload.go

i have officially pasted this url wrong one too many times

remove the period after the successful lsif upload url

---

cmd/src/campaigns_common.go

I hit merge too early in https://github.com/sourcegraph/src-cli/pull/323 and forgot to do this refactoring in it.
So, here we go. Upside: easier to review :)

Refactor progress printer for spec execution into own function

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
cmd/src/campaigns_common.go
cmd/src/campaigns_new.go
internal/campaigns/executor.go
internal/campaigns/run_steps.go
internal/output/_examples/main.go
internal/output/output.go
internal/output/progress_tty.go
internal/output/progress_with_status_bars.go
internal/output/progress_with_status_bars_simple.go
internal/output/progress_with_status_bars_tty.go
internal/output/status_bar.go
internal/output/visible_string_width.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/14449 by adding a `src campaign new` command.
Screenshot:

Add 'campaigns new' command

---

CHANGELOG.md
cmd/src/campaigns_apply.go
cmd/src/campaigns_common.go
cmd/src/campaigns_preview.go
internal/campaigns/service.go

partial fix for https://github.com/sourcegraph/sourcegraph/issues/15058

if namespace is omitted, default to username

---

CHANGELOG.md

prepping for 3.21.9 release
(note: I will add in the unreleased changes section to the changelog post-release)

releasing 3.21.9

---

CHANGELOG.md
cmd/src/campaign_progress_printer.go
cmd/src/campaigns_common.go
internal/campaigns/executor.go
internal/output/progress.go
internal/output/progress_simple.go
internal/output/progress_tty.go

This fixes https://github.com/sourcegraph/sourcegraph/issues/15607.

Add stats to progress bar

---

internal/campaigns/run_steps.go

This would have made debugging an issue earlier today a bit easier.

campaigns: add a preparing step progress message

---

README.markdown

@LawnGnome Taking a stab at updating the readme to reduce the confusion I ran into when setting up. Do you mind taking a look and confirming it looks okay?

Adding environment variable clarification to readme

---

cmd/src/extensions_publish.go

I was going to push this to `main`, but then who would see my funny commit message?

Restore balance (by adding missing parenthesis in help string)

---

cmd/src/search_stream.go

If we hit the display limit we display the statistics with a "+". This
is misleading, since the result count is accurate. So we update the
logic to be the same as used in the webapp.

search: only indicate limit hit if reasons say so

---

CHANGELOG.md
internal/batches/batch_spec.go
internal/batches/executor/changeset_specs.go
internal/batches/executor/changeset_specs_test.go
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/executor_test.go
internal/batches/executor/main_test.go
internal/batches/features.go
internal/batches/service/service.go
schema/batch_spec.schema.json
schema/batch_spec_stringdata.go

The first part of sourcegraph/sourcegraph#18277.

batches: make published field optional

---

internal/batches/service/service.go
internal/batches/service/service_test.go

@eseliger found this potential bug. It's extracted from the other PR with the tests fixed.

Use correct ref when finding directories in repos

---

.vscode/settings.json

Port over some things that are set in our main repo that are nice to have. :)

Add configuration for VSCode

---

go.mod
go.sum
internal/batches/executor/run_steps.go

PR on the other side: https://github.com/sourcegraph/sourcegraph/pull/24654

Upgrade lib to have fix for PipeOutput deadlock

---

go.mod
go.sum
internal/batches/ui/json_lines.go

Includes the types for the JSON lines UI.

Use latest lib version

---

CHANGELOG.md
cmd/src/search.go

search: check whether we can use "less" before trying to use it

---

go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/coordinator_test.go
internal/batches/executor/execution_cache.go
internal/batches/executor/execution_cache_test.go
internal/batches/executor/task.go

Counterpart to https://github.com/sourcegraph/sourcegraph/pull/27070

Use the extracted batches/execution/cache package and remove extracted code

---

go.mod
go.sum
internal/batches/executor/coordinator.go
internal/batches/executor/task.go

Counterpart to https://github.com/sourcegraph/sourcegraph/pull/27423

Make access of global env explicit when building cache keys

---

cmd/src/batch_exec.go
go.mod
go.sum

Requires https://github.com/sourcegraph/sourcegraph/pull/27562

Use latest lib

---

CHANGELOG.md
internal/batches/service/workspaces.go
internal/batches/service/workspaces_test.go

See https://github.com/sourcegraph/sourcegraph/pull/28230 for more details.

Backport fix for workspace globbing

---

internal/batches/ui/task_exec_tui_test.go

@mrnugget suggested this test, and quite right he was, too.

batches: test the fix in #666

---

go.mod
go.sum

Paired for https://github.com/sourcegraph/sourcegraph/pull/29975

bump sourcegraph/sourcegraph/lib

---

.tool-versions

Found this useful while configuring my editor on the new laptop.

asdf: Add some more commonly used tools

---

internal/batches/workspace/workspace_test.go

batches: fix workspace detection test on M1 Macs

---

cmd/src/lsif_upload.go
cmd/src/lsif_upload_flags.go
go.mod
go.sum

Related: sourcegraph/sourcegraph#32402.
Tested by hand on local instance.

lsif upload: Send indexer version witih upload request

---

CHANGELOG.md

Prepare changelog for 3.40 release

---

CHANGELOG.md

Update changelog for 3.40.1

---

CHANGELOG.md

Not available. These are just release notes changes.

Add release notes for 3.40.2

---

.github/workflows/goreleaser.yml

Cut a new release and see the CI job complete.

Fix silly quote bug

---

internal/batches/docker/image.go
internal/batches/docker/image_test.go

Docker Desktop seems to be prone to occasionally entering states where it is nominally available (in the sense that it listens for connections), but can't actually do anything useful. Memory exhaustion events from previous `src batch` runs tend to be the culprit here.
This seems to be most easily detectable by looking at the behaviour of `docker image inspect`. This command doesn't have to hit the network, nor does it perform any real work, so it should always be "quick". If it's not, that implies that Docker is not in a happy place.
This commit adds a five second timeout to `docker image inspect` invocations, along with a secret environment variable to adjust this behaviour. If `docker` times out, then a (hopefully) helpful error message is generated to hint towards the things that the …

docker: use a short timeout when inspecting images

---

CHANGELOG.md

Prepare changelog for 3.40.11

---

CHANGELOG.md

Prepare changelog for 3.41.0

---

go.mod
go.sum

This mainly includes the patch https://github.com/sourcegraph/sourcegraph/pull/38765
Upstream tests

deps: upgrade sourcegraph/lib

---

CHANGELOG.md

Add changelog for 3.42.0

---

internal/batches/service/workspaces.go
internal/batches/service/workspaces_test.go

This is a 1:1 port of https://github.com/sourcegraph/sourcegraph/pull/36646.
Added the same test as for the sg/sg PR.

Port workspaces path fix to src-cli

---

CHANGELOG.md
cmd/src/batch_exec.go

Yay 🙃 Big brain time.
Verified errors are now logged correctly.

batches: Log error from executeBatchSpecInWorkspaces

---

release.sh

Sorry, missed this in #827. I don't think we need to revert it in #828, though.
About to test after merge.

release.sh: allow -rc.X suffixes

---

cmd/src/users_clean.go

left debug logs in the initial command
https://media.giphy.com/media/eH2uOQEmvcqcqgPoH3/giphy.gif
tested locally

removed development printlns :facepalm:

---

CHANGELOG.md

changelog: add 4.0.0 section

---

go.mod
go.sum

Manually tested conversion and checked that index is changed.

chore: Bump scip dependency for Relationship.is_definition.

---

CHANGELOG.md

Just updating the changelog for next version (4.0.1)

Update changelog for next release version

---

go.mod
go.sum

Manually tested that the fix works.

chore: Bump scip dependency for LSIF conversion fix.

---

internal/batches/service/remote.go

batches: fix whitespace problem introduced in #860

---

cmd/src/search.go

single link change - no test reqd

Changed query syntax link to correct page

---

cmd/src/code_intel_upload.go

Came across this dead link 😬 
The link now does not 404?

Fix broken code-intel link

---

CHANGELOG.md

Add changelog entry for 4.1.1

---

CHANGELOG.md

Prepare changelog for 4.2.0

---

cmd/src/users_prune.go

users_prune: correct query formatting

---

cmd/src/code_intel_upload_flags.go
go.mod
go.sum

This PR improves the default file choice flow so that SCIP files are picked up by default when they exist.
Tested by hand with old/new instance on lsif/scip input. All test cases worked as expected.

codeintel upload: Improve default file based on wd

---

CHANGELOG.md
cmd/src/batch_repositories.go

Closes https://github.com/sourcegraph/src-cli/issues/914
Verified the issue is resolved.

Fix src batch repo file parameter parsing

---

cmd/src/snapshot_testcmd.go

snapshot: fix incorrect ref to validation error

---

CHANGELOG.md

Prep changelog for 4.4.2 release

---

CHANGELOG.md

update changelog for 4.5 release

---

cmd/src/validate_kube.go
internal/validate/kube/kube.go

add side effect imports for azure and gcp auth

---

CHANGELOG.md
CODEOWNERS

See title 
Just a changelog change

Add changelog entries for Own-related additions

---

CHANGELOG.md

Update `CHANGELOG.md` with changes needed for 5.0.2 release in step with `DEVELOPMENT.md` instructions.
Ran `go test ./...` with all tests passing

Release: update CHANGELOG.md for release process of 5.0.2

---

go.mod

Fix git state error in build
Ran `go test ./...` with all tests passing.

Fix: fix `go.mod` dirty state error in build

---

CHANGELOG.md

Update `CHANGELOG.md` with changes needed for 5.0.3 release in step with `DEVELOPMENT.md` instructions.
Ran go test ./... with all tests passing

Release: update CHANGELOG.md for release process of 5.0.3

---

.github/workflows/docker.yml
.github/workflows/goreleaser.yml

Use docker credentials from environment instead of hardcoded
N/A

reference docker user

---

CHANGELOG.md

changelog: cut sourcegraph@5.1.0
N/A

changelog: cut sourcegraph@5.1.0

---

.github/workflows/goreleaser-check.yml
.goreleaser.yml

Update workflows to use newer action
Go releaser action passes

go-releaser: upgrade workflow

---

CHANGELOG.md
internal/instancehealth/checks.go
internal/instancehealth/checks_test.go
internal/instancehealth/summary.go

looks like this was renamed
Tested data migration process

instancehealth: permissionSyncJobs -> permissionsSyncJobs

---

CHANGELOG.md

changelog update 5.1.1.

---

README.md

README: fix PowerShell env var instructions

---

internal/batches/docker/info.go

See error here: https://github.com/sourcegraph/src-cli/actions/runs/5948515857/job/16132445754#step:4:21
- N/A

ci: fix goimports lint

---

CHANGELOG.md

5.1.2 changelog update

---

cmd/src/code_intel.go
cmd/src/code_intel_upload.go

docs: Mention SCIP not just LSIF

---

CHANGELOG.md

changelog: cut sourcegraph@5.2.0
N/A

changelog: cut sourcegraph@5.2.0

---

CHANGELOG.md

changelog update 5.2.1

---

CHANGELOG.md

changelog: cut sourcegraph@5.3.0
N/A

changelog: cut sourcegraph@5.3.0

---

.github/workflows/scip.yml

Fixes GRAPH-597
Tokens are now required
Check that uploads work for this PR

Fix SCIP uploads in CI

---

cmd/src/code_intel_upload.go

Fix lint error due to variable name mixup

---

.goreleaser-patch.yml

Same go command regression as previous commit. We just forgot a goreleaser file.
Manually ran `go generate ./...`

fix .goreleaser-patch.yml

---

CHANGELOG.md

docs: Add CHANGELOG entries for v5.4.0

---

CHANGELOG.md

misc(changelog): prepare for 5.5.0 release

---

CHANGELOG.md

Visual testing: view CHANGELOG and ensure link works.

Fix PR link - 312 --> 317

---

.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/goreleaser-check.yml
.github/workflows/goreleaser.yml
.github/workflows/scip.yml

We need to tell git to use the token
Successful [Go CI run](https://github.com/sourcegraph/src-cli/actions/runs/11144684742/job/30972510942?pr=1113)

add required github config

---

CHANGELOG.md

Add changelog entry section for 5.9.0 release.
CI

chore(rel): 5.9.0: Update changelog

---

CHANGELOG.md

5.10 changelong entry

---

cmd/src/gateway_benchmark.go
dev/golangci-lint.sh

Hopefully solves a potential OOM we are seeing on CI.
Test Plan: CI

chore/ci: upgrade golanglint-ci to 1.64.5

---

cmd/src/login.go

Cosmetic change in output message

Fixed broken link in error message in login.go

---

.github/workflows/goreleaser.yml

Update missed secret
CI, run the release process

chore: update secrets v2

---

CHANGELOG.md

Update changelog for 6.5.0 release
CI

feat(rel): update changelog with 6.5.0

---

CHANGELOG.md

Add changelog entry for 6.7.0
CI

chore(rel): update changelog

---

CHANGELOG.md

Update changelog for 6.7.1104
